import BealRegular.AdjoinRootFactorization

#print axioms BealRegular.AdjoinRootFactorization.irreducible_of_adjoinRoot_isField
#print axioms BealRegular.AdjoinRootFactorization.irreducible_of_adjoinRoot_algEquiv_isField
#print axioms BealRegular.AdjoinRootFactorization.exists_two_irreducible_factors_of_adjoinRoot_algEquiv_prod
#print axioms BealRegular.AdjoinRootFactorization.irreducible_of_adjoinRoot_algEquiv_adjoinRoot
#print axioms BealRegular.AdjoinRootFactorization.exists_two_irreducible_factors_of_adjoinRoot_algEquiv_adjoinRoots
