module

public import Mathlib.Algebra.Polynomial.AlgebraMap
public import Mathlib.NumberTheory.NumberField.ClassNumber
public import Mathlib.NumberTheory.NumberField.Ideal.KummerDedekind
public import Mathlib.RingTheory.Ideal.Operations

/-!
# Polynomial certificates for principal Kummer--Dedekind ideals

Three exact polynomial identities certify that the two-generated ideal
`(q, F(theta))` is generated by a displayed element `G(theta)`.  A second
generic theorem transports principality between primes over the same rational
prime in a Galois number field.
-/

@[expose] public section

open Ideal Polynomial

namespace BealRegular.PrincipalIdealCertificate

/-- A three-identity certificate proving that a two-generated ideal is
principal. -/
theorem span_pair_eq_span_singleton_of_certificate
    {R : Type*} [CommRing R]
    {a b g qa qb ca cb : R}
    (ha : a = g * qa)
    (hb : b = g * qb)
    (hg : g = ca * a + cb * b) :
    (span {a, b} : Ideal R) = span {g} := by
  apply le_antisymm
  · rw [Ideal.span_le]
    intro x hx
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
    rcases hx with rfl | rfl
    · rw [ha]
      exact (span {g}).mul_mem_right qa
        (Ideal.mem_span_singleton_self g)
    · rw [hb]
      exact (span {g}).mul_mem_right qb
        (Ideal.mem_span_singleton_self g)
  · rw [Ideal.span_le, Set.singleton_subset_iff]
    rw [hg]
    exact (span {a, b}).add_mem
      ((span {a, b}).mul_mem_left ca (Ideal.subset_span (by simp)))
      ((span {a, b}).mul_mem_left cb (Ideal.subset_span (by simp)))

/-- The equality certificate packaged as `Submodule.IsPrincipal`. -/
theorem span_pair_isPrincipal_of_certificate
    {R : Type*} [CommRing R]
    {a b g qa qb ca cb : R}
    (ha : a = g * qa)
    (hb : b = g * qb)
    (hg : g = ca * a + cb * b) :
    Submodule.IsPrincipal (span {a, b} : Ideal R) :=
  ⟨g, span_pair_eq_span_singleton_of_certificate ha hb hg⟩

/-- Evaluate the three polynomial identities modulo `Phi(theta) = 0`. -/
theorem span_pair_eq_span_singleton_of_aeval_certificate
    {S R : Type*} [CommRing S] [CommRing R] [Algebra S R]
    (theta : R)
    {A B G Phi QA QB RA RB RG CA CB : S[X]}
    (hPhi : aeval theta Phi = 0)
    (hA : A = G * QA + Phi * RA)
    (hB : B = G * QB + Phi * RB)
    (hG : G = CA * A + CB * B + Phi * RG) :
    (span {aeval theta A, aeval theta B} : Ideal R) =
      span {aeval theta G} := by
  apply span_pair_eq_span_singleton_of_certificate
      (qa := aeval theta QA) (qb := aeval theta QB)
      (ca := aeval theta CA) (cb := aeval theta CB)
  · simpa only [map_add, map_mul, hPhi, zero_mul, add_zero] using
      congrArg (aeval theta) hA
  · simpa only [map_add, map_mul, hPhi, zero_mul, add_zero] using
      congrArg (aeval theta) hB
  · simpa only [map_add, map_mul, hPhi, zero_mul, add_zero] using
      congrArg (aeval theta) hG

/-- Kummer--Dedekind specialization for the ideal `(q, F(theta))`. -/
theorem kummerDedekindIdeal_eq_span_singleton_of_polynomial_certificate
    {S R : Type*} [CommRing S] [CommRing R] [Algebra S R]
    (theta : R) (q : S)
    {F G Phi QA QB RA RB RG CA CB : S[X]}
    (hPhi : aeval theta Phi = 0)
    (hq : C q = G * QA + Phi * RA)
    (hF : F = G * QB + Phi * RB)
    (hG : G = CA * C q + CB * F + Phi * RG) :
    (span {algebraMap S R q, aeval theta F} : Ideal R) =
      span {aeval theta G} := by
  simpa only [aeval_C] using
    span_pair_eq_span_singleton_of_aeval_certificate theta hPhi hq hF hG

/-- Principal-ideal endpoint for the Kummer--Dedekind certificate. -/
theorem kummerDedekindIdeal_isPrincipal_of_polynomial_certificate
    {S R : Type*} [CommRing S] [CommRing R] [Algebra S R]
    (theta : R) (q : S)
    {F G Phi QA QB RA RB RG CA CB : S[X]}
    (hPhi : aeval theta Phi = 0)
    (hq : C q = G * QA + Phi * RA)
    (hF : F = G * QB + Phi * RB)
    (hG : G = CA * C q + CB * F + Phi * RG) :
    Submodule.IsPrincipal
      (span {algebraMap S R q, aeval theta F} : Ideal R) :=
  ⟨aeval theta G,
    kummerDedekindIdeal_eq_span_singleton_of_polynomial_certificate
      theta q hPhi hq hF hG⟩

/-- A selected prime from Mathlib's Kummer--Dedekind equivalence is principal
when its lifted factor admits the three polynomial identities. -/
theorem kummerDedekindPrime_isPrincipal_of_polynomial_certificate
    {K : Type*} [Field K] [NumberField K]
    (theta : NumberField.RingOfIntegers K)
    {p : ℕ} [Fact p.Prime]
    (hp : ¬ p ∣ RingOfIntegers.exponent theta)
    {F G Phi QA QB RA RB RG CA CB : ℤ[X]}
    (hFactor : F.map (Int.castRingHom (ZMod p)) ∈
      RingOfIntegers.monicFactorsMod theta p)
    (hPhi : aeval theta Phi = 0)
    (hq : C (p : ℤ) = G * QA + Phi * RA)
    (hF : F = G * QB + Phi * RB)
    (hG : G = CA * C (p : ℤ) + CB * F + Phi * RG) :
    Submodule.IsPrincipal
      ((((NumberField.Ideal.primesOverSpanEquivMonicFactorsMod hp).symm
        ⟨F.map (Int.castRingHom (ZMod p)), hFactor⟩ :
          Ideal.primesOver (span {(p : ℤ)})
            (NumberField.RingOfIntegers K)) :
          Ideal (NumberField.RingOfIntegers K))) := by
  rw [NumberField.Ideal.primesOverSpanEquivMonicFactorsMod_symm_apply_eq_span
    hp hFactor]
  simpa using
    (kummerDedekindIdeal_isPrincipal_of_polynomial_certificate
      theta (p : ℤ) hPhi hq hF hG)

/-- In a Galois number field, principality transports between primes over the
same base prime. -/
theorem isPrincipal_of_liesOver_of_isGalois
    {K : Type*} [Field K] [NumberField K] [IsGalois ℚ K]
    (p : Ideal ℤ) [p.IsMaximal]
    (Q P : Ideal (NumberField.RingOfIntegers K)) [Q.IsPrime] [P.IsPrime]
    [Q.LiesOver p] [P.LiesOver p]
    (hQ : Submodule.IsPrincipal Q) :
    Submodule.IsPrincipal P := by
  obtain ⟨sigma, hsigma⟩ :=
    Ideal.exists_smul_eq_of_isGaloisGroup p Q P (K ≃ₐ[ℚ] K)
  rw [← hsigma, Ideal.pointwise_smul_def]
  exact hQ.map_ringHom
    (MulSemiringAction.toRingHom (K ≃ₐ[ℚ] K)
      (NumberField.RingOfIntegers K) sigma)

end BealRegular.PrincipalIdealCertificate
