import BealRegular.PrincipalIdealCertificate

#print axioms BealRegular.PrincipalIdealCertificate.span_pair_eq_span_singleton_of_certificate
#print axioms BealRegular.PrincipalIdealCertificate.span_pair_isPrincipal_of_certificate
#print axioms BealRegular.PrincipalIdealCertificate.span_pair_eq_span_singleton_of_aeval_certificate
#print axioms BealRegular.PrincipalIdealCertificate.kummerDedekindIdeal_eq_span_singleton_of_polynomial_certificate
#print axioms BealRegular.PrincipalIdealCertificate.kummerDedekindIdeal_isPrincipal_of_polynomial_certificate
#print axioms BealRegular.PrincipalIdealCertificate.kummerDedekindPrime_isPrincipal_of_polynomial_certificate
#print axioms BealRegular.PrincipalIdealCertificate.isPrincipal_of_liesOver_of_isGalois
