import BealRegular.Signature357SevenAdicEisenstein

#print axioms BealRegular.Signature357SevenAdicEisenstein.sevenAdicMaximalIdeal
#print axioms BealRegular.Signature357SevenAdicEisenstein.seven_not_mem_maximalIdeal_sq
#print axioms BealRegular.Signature357SevenAdicEisenstein.septicIntegralPolynomial
#print axioms BealRegular.Signature357SevenAdicEisenstein.septicIntegralPolynomial_isEisenstein
#print axioms BealRegular.Signature357SevenAdicEisenstein.radicalIntegralPolynomial
#print axioms BealRegular.Signature357SevenAdicEisenstein.radicalIntegralPolynomial_isEisenstein
#print axioms BealRegular.Signature357SevenAdicEisenstein.septicSevenAdic_irreducible
#print axioms BealRegular.Signature357SevenAdicEisenstein.radicalSevenAdic_irreducible
