import BealRegular.Signature357GlobalFactorShape

#print axioms BealRegular.Signature357GlobalFactorShape.monic_factor_shape_of_map_eq_two_irreducibles
#print axioms BealRegular.Signature357GlobalFactorShape.HasTwoIrreducibleFactorsOfDegrees
#print axioms BealRegular.Signature357GlobalFactorShape.HasSignature357FactorShape
#print axioms BealRegular.Signature357GlobalFactorShape.irreducible_or_hasTwoFactorsOfDegrees_of_map
#print axioms BealRegular.Signature357GlobalFactorShape.hasSignature357FactorShape_of_map
#print axioms BealRegular.Signature357GlobalFactorShape.rationalMonicFiber
#print axioms BealRegular.Signature357GlobalFactorShape.rationalMonicFiber_monic
#print axioms BealRegular.Signature357GlobalFactorShape.rationalMonicFiber_natDegree
#print axioms BealRegular.Signature357GlobalFactorShape.rationalMonicFiber_associated_fiberK
#print axioms BealRegular.Signature357GlobalFactorShape.rationalMonicFiber_irreducible_of_sevenAdic
#print axioms BealRegular.Signature357GlobalFactorShape.rationalMonicFiber_factorShape_of_sevenAdic_factorization
#print axioms BealRegular.Signature357GlobalFactorShape.rationalMonicFiber_hasFactorShape_of_sevenAdic
