module

public import BealRegular.TwentyThreeRealSubfieldRingOfIntegers
public import Mathlib.FieldTheory.Galois.Abelian
public import Mathlib.RingTheory.Norm.Basic

/-!
# Class-number reduction for the maximal real subfield at 23

The maximal real subfield is Galois over `ℚ`.  Its exact Minkowski bound
reduces class number one to one selected prime above each rational prime at
most `900`.  The unique ramified rational prime `23` is discharged explicitly
by the principal ideal generated by the Eisenstein element `betaInteger`.
-/

@[expose] public section

open Ideal NumberField Polynomial
open RingOfIntegers
open scoped nonZeroDivisors

namespace BealRegular.TwentyThreeRealSubfieldClassNumber

open BealRegular.TwentyThreeRealSubfieldRingOfIntegers
open BealRegular.TwentyThreeRealSubfieldEisenstein

noncomputable section

local notation "K23" => CyclotomicField 23 ℚ
local notation "K23plus" => NumberField.maximalRealSubfield K23

local instance : IsCyclotomicExtension {23} ℚ K23 :=
  CyclotomicField.instIsCyclotomicExtensionSingletonNatSetOfCharZero 23 ℚ

local instance : IsAbelianGalois ℚ K23 :=
  IsCyclotomicExtension.isAbelianGalois {23} ℚ K23

noncomputable def K23plusIntermediateField : IntermediateField ℚ K23 :=
  (NumberField.maximalRealSubfield K23).toIntermediateField (by
    intro x
    rw [NumberField.mem_maximalRealSubfield_iff]
    intro phi
    simp)

local instance : IsAbelianGalois ℚ K23plusIntermediateField :=
  IsAbelianGalois.tower_bot ℚ K23plusIntermediateField K23

/-- The maximal real subfield of the 23rd cyclotomic field is Galois over
`ℚ`. -/
noncomputable instance maximalRealSubfield_isGalois : IsGalois ℚ K23plus := by
  change IsGalois ℚ K23plusIntermediateField
  infer_instance

/-- The explicit prime ideal above `23`, generated by the Eisenstein element
`betaInteger`. -/
noncomputable def betaPrimeIdeal :
    Ideal (NumberField.RingOfIntegers K23plus) :=
  span ({betaInteger} : Set (NumberField.RingOfIntegers K23plus))

theorem norm_betaInteger : Algebra.norm ℤ betaInteger = 23 := by
  rw [← ringOfIntegersPowerBasis_gen,
    Algebra.PowerBasis.norm_gen_eq_coeff_zero_minpoly,
    ringOfIntegersPowerBasis_dim,
    ringOfIntegersPowerBasis_gen,
    minpoly_int_betaInteger]
  norm_num [shiftedRealSubfieldPolynomial, Polynomial.coeff_X,
    Polynomial.coeff_C_mul, Polynomial.coeff_sub, Polynomial.coeff_add,
    pow_succ]

theorem absNorm_betaPrimeIdeal : absNorm betaPrimeIdeal = 23 := by
  rw [betaPrimeIdeal, Ideal.absNorm_span_singleton, norm_betaInteger]
  norm_num

theorem betaPrimeIdeal_isPrime : betaPrimeIdeal.IsPrime := by
  apply Ideal.isPrime_of_irreducible_absNorm
  rw [absNorm_betaPrimeIdeal]
  exact Nat.irreducible_iff_prime.mpr
    (Nat.prime_iff.mp (by norm_num : Nat.Prime 23))

theorem betaPrimeIdeal_liesOver :
    betaPrimeIdeal.LiesOver (span ({(23 : ℤ)} : Set ℤ)) := by
  have hnormPrime : (absNorm betaPrimeIdeal).Prime := by
    rw [absNorm_betaPrimeIdeal]
    norm_num
  rw [Ideal.liesOver_iff]
  rw [Ideal.under_def,
    ← Ideal.span_singleton_absNorm (I := betaPrimeIdeal) hnormPrime,
    absNorm_betaPrimeIdeal]
  norm_num

theorem betaPrimeIdeal_mem_primesOver :
    betaPrimeIdeal ∈ primesOver (span ({(23 : ℤ)} : Set ℤ))
      (NumberField.RingOfIntegers K23plus) :=
  ⟨betaPrimeIdeal_isPrime, betaPrimeIdeal_liesOver⟩

theorem betaPrimeIdeal_isPrincipal :
    Submodule.IsPrincipal betaPrimeIdeal := by
  exact ⟨betaInteger, rfl⟩

/-- With the exact Minkowski floor `900`, one suitable selected prime above
each rational prime in `[1, 900]` proves that the real ring of integers is a
principal ideal ring. -/
theorem isPrincipalIdealRing_of_one_prime_above
    (h : ∀ (p : ℕ), p ∈ Finset.Icc 1 900 → p.Prime →
      ∃ P ∈ primesOver (span ({(p : ℤ)} : Set ℤ))
          (NumberField.RingOfIntegers K23plus),
        900 < p ^ P.inertiaDeg ℤ ∨ Submodule.IsPrincipal P) :
    IsPrincipalIdealRing (NumberField.RingOfIntegers K23plus) := by
  apply
    isPrincipalIdealRing_of_isPrincipal_of_lt_or_isPrincipal_of_mem_primesOver_of_mem_Icc
  change ∀ p ∈ Finset.Icc 1 ⌊realMinkowskiBound⌋₊, p.Prime →
    ∃ P ∈ primesOver (span ({(p : ℤ)} : Set ℤ))
        (NumberField.RingOfIntegers K23plus),
      ⌊realMinkowskiBound⌋₊ < p ^ P.inertiaDeg ℤ ∨
        Submodule.IsPrincipal P
  rw [realMinkowskiBound_floor]
  exact h

theorem classNumber_eq_one_of_one_prime_above
    (h : ∀ (p : ℕ), p ∈ Finset.Icc 1 900 → p.Prime →
      ∃ P ∈ primesOver (span ({(p : ℤ)} : Set ℤ))
          (NumberField.RingOfIntegers K23plus),
        900 < p ^ P.inertiaDeg ℤ ∨ Submodule.IsPrincipal P) :
    NumberField.classNumber K23plus = 1 :=
  NumberField.classNumber_eq_one_iff.mpr
    (isPrincipalIdealRing_of_one_prime_above h)

/-- The ramified prime `23` satisfies the Minkowski criterion through the
explicit principal ideal `(betaInteger)`. -/
theorem prime_twentyThree_branch :
    ∃ P ∈ primesOver (span ({(23 : ℤ)} : Set ℤ))
        (NumberField.RingOfIntegers K23plus),
      900 < 23 ^ P.inertiaDeg ℤ ∨ Submodule.IsPrincipal P := by
  exact ⟨betaPrimeIdeal, betaPrimeIdeal_mem_primesOver,
    Or.inr betaPrimeIdeal_isPrincipal⟩

/-- It is enough to discharge only rational primes other than `23`; the
ramified prime is supplied by `prime_twentyThree_branch`. -/
theorem isPrincipalIdealRing_of_other_primes
    (h : ∀ (p : ℕ), p ∈ Finset.Icc 1 900 → p.Prime → p ≠ 23 →
      ∃ P ∈ primesOver (span ({(p : ℤ)} : Set ℤ))
          (NumberField.RingOfIntegers K23plus),
        900 < p ^ P.inertiaDeg ℤ ∨ Submodule.IsPrincipal P) :
    IsPrincipalIdealRing (NumberField.RingOfIntegers K23plus) := by
  apply isPrincipalIdealRing_of_one_prime_above
  intro p hpRange hpPrime
  by_cases hp : p = 23
  · subst p
    exact prime_twentyThree_branch
  · exact h p hpRange hpPrime hp

theorem classNumber_eq_one_of_other_primes
    (h : ∀ (p : ℕ), p ∈ Finset.Icc 1 900 → p.Prime → p ≠ 23 →
      ∃ P ∈ primesOver (span ({(p : ℤ)} : Set ℤ))
          (NumberField.RingOfIntegers K23plus),
        900 < p ^ P.inertiaDeg ℤ ∨ Submodule.IsPrincipal P) :
    NumberField.classNumber K23plus = 1 :=
  NumberField.classNumber_eq_one_iff.mpr
    (isPrincipalIdealRing_of_other_primes h)

end

end BealRegular.TwentyThreeRealSubfieldClassNumber
