import BealRegular.TwentyThreeRamifiedPrime

#print axioms BealRegular.TwentyThreeRamifiedPrime.primeIdealTwentyThree_mem_primesOver
#print axioms BealRegular.TwentyThreeRamifiedPrime.primesOver_twentyThree_ncard
#print axioms BealRegular.TwentyThreeRamifiedPrime.primeIdealTwentyThree_eq_span_generator
#print axioms BealRegular.TwentyThreeRamifiedPrime.generator_pow_twentyTwo_associated_twentyThree
#print axioms BealRegular.TwentyThreeRamifiedPrime.primeIdealTwentyThree_inertiaDeg
#print axioms BealRegular.TwentyThreeRamifiedPrime.primeIdealTwentyThree_ramificationIdx
#print axioms BealRegular.TwentyThreeRamifiedPrime.primeIdealTwentyThree_isPrincipal
#print axioms BealRegular.TwentyThreeRamifiedPrime.primeIdealTwentyThree_cube_eq_span_generator_pow
#print axioms BealRegular.TwentyThreeRamifiedPrime.primeIdealTwentyThree_cube_isPrincipal
#print axioms BealRegular.TwentyThreeRamifiedPrime.exists_prime_above_twentyThree_cube_isPrincipal
#print axioms BealRegular.TwentyThreeRamifiedPrime.one_prime_above_cubes_of_not_two_three_twentyThree
