module

public import BealRegular.TwentyThreeRealCertificateBase

/-!
This file is generated by `render_23_real_certificates.mjs` from
`certificates_23_real.json`.  Corpus SHA-256:
`21e554a6a6a2b0d78efef741813a98d5269feebdbf11f9219bb6f8c03d6cc9e7`.
Do not edit this file by hand.
-/

@[expose] public section

open Ideal NumberField Polynomial RingOfIntegers

namespace BealRegular.TwentyThreeRealCertificates.Q827

open BealRegular.PrincipalIdealCertificate
open BealRegular.TwentyThreeRealCertificateBase

noncomputable section

local instance : Fact (Nat.Prime 827) := ⟨by norm_num⟩

def P : ℤ[X] := X - C 17

def Q : ℤ[X] := X ^ 10 + C 16 * X ^ 9 + C 262 * X ^ 8 + C 4463 * X ^ 7 + C 75907 * X ^ 6
  + C 1290391 * X ^ 5 + C 21936591 * X ^ 4 + C 372922082 * X ^ 3 + C 6339675429 * X ^ 2
  + C 107774482278 * X + C 1832166198720

def A : ℤ[X] := C 37662424883

def G : ℤ[X] := X ^ 9 - X ^ 8 - C 9 * X ^ 7 + C 7 * X ^ 6 + C 27 * X ^ 5 - C 14 * X ^ 4
  - C 30 * X ^ 3 + C 7 * X ^ 2 + C 9 * X

def Qq : ℤ[X] := -C 86 * X ^ 10 + C 278 * X ^ 9 + C 624 * X ^ 8 - C 2571 * X ^ 7 - C 1318 * X ^ 6
  + C 8120 * X ^ 5 + C 612 * X ^ 4 - C 9973 * X ^ 3 + C 292 * X ^ 2 + C 3773 * X + C 151

def Rq : ℤ[X] := C 86 * X ^ 8 - C 278 * X ^ 7 - C 538 * X ^ 6 + C 2207 * X ^ 5 + C 972 * X ^ 4
  - C 5355 * X ^ 3 - C 991 * X ^ 2 + C 3603 * X + C 827

def QP : ℤ[X] := C 2 * X ^ 10 - C 6 * X ^ 9 - C 15 * X ^ 8 + C 55 * X ^ 7 + C 34 * X ^ 6
  - C 172 * X ^ 5 - C 21 * X ^ 4 + C 209 * X ^ 3 - C 3 * X ^ 2 - C 78 * X - C 3

def RP : ℤ[X] := -C 2 * X ^ 8 + C 6 * X ^ 7 + C 13 * X ^ 6 - C 47 * X ^ 5 - C 25 * X ^ 4
  + C 112 * X ^ 3 + C 24 * X ^ 2 - C 74 * X - C 17

def C1 : ℤ[X] := X ^ 8 + C 16 * X ^ 7 + C 263 * X ^ 6 + C 4478 * X ^ 5 + C 76153 * X ^ 4
  + C 1294587 * X ^ 3 + C 22007949 * X ^ 2 + C 374135140 * X + C 6360297389

def C2 : ℤ[X] := C 130743719

set_option maxHeartbeats 0 in
-- Exact normalization of the displayed polynomial identity can be expensive.
set_option maxRecDepth 12000 in
/-- The factor identity in ℤ[X]. -/
theorem factorization_identity :
    P * Q + C (827 : ℤ) * A = Phi := by
  simp only [P, Q, A, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  ring

set_option maxHeartbeats 0 in
-- Exact normalization of the three displayed Bezout identities can be expensive.
set_option maxRecDepth 12000 in
/-- The three exact Bezout identities certifying the Kummer--Dedekind ideal. -/
theorem principal_identities :
    C (827 : ℤ) = G * Qq + Phi * Rq ∧
      P = G * QP + Phi * RP ∧
        G = C2 * C (827 : ℤ) + C1 * P + Phi * 0 := by
  simp only [P, G, Qq, Rq, QP, RP, C1, C2, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  constructor
  · ring
  constructor <;> ring

theorem P_monic : P.Monic := by
  simp only [P]
  monicity!

theorem map_P_irreducible :
    Irreducible (P.map (Int.castRingHom (ZMod 827))) := by
  apply Polynomial.irreducible_of_degree_eq_one
  simp only [P, Polynomial.map_sub, map_X, map_C]
  compute_degree!

theorem map_P_dvd_Phi :
    P.map (Int.castRingHom (ZMod 827)) ∣
      Phi.map (Int.castRingHom (ZMod 827)) := by
  refine ⟨Q.map (Int.castRingHom (ZMod 827)), ?_⟩
  have h := congrArg (Polynomial.map (Int.castRingHom (ZMod 827)))
    factorization_identity
  simp only [Polynomial.map_add, Polynomial.map_mul, map_C] at h
  have hq : Int.castRingHom (ZMod 827) (827 : ℤ) = 0 := by decide
  rw [hq, C_0, zero_mul, add_zero] at h
  exact h.symm

theorem map_P_mem_monicFactorsMod :
    P.map (Int.castRingHom (ZMod 827)) ∈ monicFactorsMod theta 827 := by
  rw [Multiset.mem_toFinset, Polynomial.mem_normalizedFactors_iff
    (map_monic_ne_zero (minpoly.monic theta.isIntegral))]
  refine ⟨map_P_irreducible, P_monic.map _, ?_⟩
  rw [← Phi_eq_minpoly]
  exact map_P_dvd_Phi

theorem q_not_dvd_exponent : ¬ 827 ∣ exponent theta := by
  rw [theta_exponent]
  norm_num

/-- The prime above 827 selected by the displayed linear factor. -/
noncomputable def selectedPrime :
    primesOver (span {(827 : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  (NumberField.Ideal.primesOverSpanEquivMonicFactorsMod q_not_dvd_exponent).symm
    ⟨P.map (Int.castRingHom (ZMod 827)), map_P_mem_monicFactorsMod⟩

theorem selectedPrime_mem_primesOver :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) ∈
      primesOver (span {(827 : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  selectedPrime.property

theorem selectedPrime_eq_span :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) =
      span {algebraMap ℤ (NumberField.RingOfIntegers RealField) 827, aeval theta P} := by
  exact NumberField.Ideal.primesOverSpanEquivMonicFactorsMod_symm_apply_eq_span
    q_not_dvd_exponent map_P_mem_monicFactorsMod

/-- The selected prime above 827 is principal, with generator G(theta). -/
theorem selectedPrime_isPrincipal :
    Submodule.IsPrincipal
      (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) := by
  rcases principal_identities with ⟨hq, hP, hG⟩
  exact kummerDedekindPrime_isPrincipal_of_polynomial_certificate
    (F := P) (G := G) (Phi := Phi) (QA := Qq) (QB := QP)
    (RA := Rq) (RB := RP) (RG := 0) (CA := C2) (CB := C1)
    (p := 827) theta q_not_dvd_exponent map_P_mem_monicFactorsMod
    aeval_Phi_theta hq hP hG

/-- The exact branch shape consumed by the real-subfield Minkowski criterion. -/
theorem minkowski_branch :
    ∃ J ∈ primesOver (span {(827 : ℤ)})
        (NumberField.RingOfIntegers RealField),
      900 < 827 ^ J.inertiaDeg ℤ ∨ Submodule.IsPrincipal J :=
  ⟨selectedPrime, selectedPrime.property, Or.inr selectedPrime_isPrincipal⟩

end

end BealRegular.TwentyThreeRealCertificates.Q827
