module

public import BealRegular.TwentyThreePrimeThreeCube
public import Mathlib.NumberTheory.NumberField.Cyclotomic.Ideal

/-!
# The ramified prime above 23 in Q(zeta_23)

The unique prime above the conductor `23` is generated by `zeta_23 - 1`.
In particular it is already principal, so its cube is principal. This closes
the ramified branch of the full-field Minkowski reduction; it does not address
the remaining unramified residue-degree-one and residue-degree-two primes.
-/

@[expose] public section

open Ideal NumberField RingOfIntegers

namespace BealRegular.TwentyThreeRamifiedPrime

noncomputable section

local notation "K23" => CyclotomicField 23 ℚ

local instance : Fact (Nat.Prime 23) :=
  ⟨BealRegular.TwentyThreePrimeTwoCube.prime_twentyThree⟩
local instance : IsCyclotomicExtension {23} ℚ K23 :=
  CyclotomicField.instIsCyclotomicExtensionSingletonNatSetOfCharZero 23 ℚ

/-- Fix one proof witness so all uses of `toInteger` share the same term. -/
theorem zeta23_spec :
    IsPrimitiveRoot (IsCyclotomicExtension.zeta 23 ℚ K23) 23 :=
  IsCyclotomicExtension.zeta_spec 23 ℚ K23

/-- The standard uniformizer `zeta_23 - 1` in the ring of integers. -/
def ramifiedGenerator : 𝓞 K23 :=
  zeta23_spec.toInteger - 1

/-- The necessarily unique prime ideal above `23`. -/
def primeIdealTwentyThree : primesOver (span {(23 : ℤ)}) (𝓞 K23) := by
  have hprime : (span {ramifiedGenerator} : Ideal (𝓞 K23)).IsPrime := by
    simpa only [ramifiedGenerator] using
      (IsCyclotomicExtension.Rat.isPrime_span_zeta_sub_one' 23 zeta23_spec)
  letI : (span {ramifiedGenerator} : Ideal (𝓞 K23)).IsPrime := hprime
  have hmem : ((23 : ℤ) : 𝓞 K23) ∈ span {ramifiedGenerator} := by
    rw [mem_span_singleton]
    change ramifiedGenerator ∣ ((23 : ℤ) : 𝓞 K23)
    simpa only [ramifiedGenerator] using
      (IsCyclotomicExtension.Rat.zeta_sub_one_dvd_intCast_iff' 23 zeta23_spec).2
        (dvd_refl (23 : ℤ))
  refine ⟨span {ramifiedGenerator}, hprime, ?_⟩
  rw [Ideal.liesOver_iff]
  refine IsMaximal.eq_of_le (Int.ideal_span_isMaximal_of_prime 23) IsPrime.ne_top' ?_
  rw [span_singleton_le_iff_mem, mem_comap, algebraMap_int_eq]
  exact hmem

theorem primeIdealTwentyThree_mem_primesOver :
    (primeIdealTwentyThree : Ideal (𝓞 K23)) ∈
      primesOver (span {(23 : ℤ)}) (𝓞 K23) :=
  primeIdealTwentyThree.property

/-- There is exactly one prime ideal above the conductor. -/
theorem primesOver_twentyThree_ncard :
    (primesOver (span {(23 : ℤ)}) (𝓞 K23)).ncard = 1 :=
  IsCyclotomicExtension.Rat.ncard_primesOver_of_prime 23 K23

/-- The chosen prime is the principal ideal generated by `zeta_23 - 1`. -/
theorem primeIdealTwentyThree_eq_span_generator :
    (primeIdealTwentyThree : Ideal (𝓞 K23)) = span {ramifiedGenerator} := by
  simpa only [ramifiedGenerator] using
    (IsCyclotomicExtension.Rat.eq_span_zeta_sub_one_of_liesOver' 23 K23
      zeta23_spec
      (primeIdealTwentyThree : Ideal (𝓞 K23)))

/-- The conductor factorization is generated by the 22nd power of the
uniformizer, up to a unit. -/
theorem generator_pow_twentyTwo_associated_twentyThree :
    Associated (ramifiedGenerator ^ 22) (23 : 𝓞 K23) := by
  simpa [ramifiedGenerator] using
    (IsCyclotomicExtension.Rat.associated_zeta_sub_one_pow_prime 23
      zeta23_spec)

theorem primeIdealTwentyThree_inertiaDeg :
    (primeIdealTwentyThree : Ideal (𝓞 K23)).inertiaDeg ℤ = 1 :=
  IsCyclotomicExtension.Rat.inertiaDeg_eq_of_prime 23 K23 primeIdealTwentyThree

theorem primeIdealTwentyThree_ramificationIdx :
    (primeIdealTwentyThree : Ideal (𝓞 K23)).ramificationIdx ℤ = 22 := by
  simpa using
    (IsCyclotomicExtension.Rat.ramificationIdx_eq_of_prime 23 K23
      (primeIdealTwentyThree : Ideal (𝓞 K23)))

theorem primeIdealTwentyThree_isPrincipal :
    Submodule.IsPrincipal (primeIdealTwentyThree : Ideal (𝓞 K23)) :=
  ⟨ramifiedGenerator, primeIdealTwentyThree_eq_span_generator⟩

theorem primeIdealTwentyThree_cube_eq_span_generator_pow :
    (primeIdealTwentyThree : Ideal (𝓞 K23)) ^ 3 = span {ramifiedGenerator ^ 3} := by
  rw [primeIdealTwentyThree_eq_span_generator, Ideal.span_singleton_pow]

theorem primeIdealTwentyThree_cube_isPrincipal :
    Submodule.IsPrincipal ((primeIdealTwentyThree : Ideal (𝓞 K23)) ^ 3) :=
  ⟨ramifiedGenerator ^ 3, primeIdealTwentyThree_cube_eq_span_generator_pow⟩

/-- The exact existential shape consumed by the ramified branch of the
one-prime-above Minkowski theorem. -/
theorem exists_prime_above_twentyThree_cube_isPrincipal :
    ∃ P ∈ primesOver (span {(23 : ℤ)}) (𝓞 K23),
      Submodule.IsPrincipal (P ^ 3) :=
  ⟨primeIdealTwentyThree, primeIdealTwentyThree.property,
    primeIdealTwentyThree_cube_isPrincipal⟩

/-- The already checked primes `2`, `3`, and `23` can be removed from the
one-prime-above Minkowski callback.  This theorem deliberately leaves every
other rational prime as an explicit hypothesis. -/
theorem one_prime_above_cubes_of_not_two_three_twentyThree
    (B : ℕ)
    (h : ∀ p ∈ Finset.Icc 1 B, p.Prime → p ≠ 2 → p ≠ 3 → p ≠ 23 →
      ∃ P ∈ primesOver (span {(p : ℤ)}) (𝓞 K23),
        B < p ^ P.inertiaDeg ℤ ∨ Submodule.IsPrincipal (P ^ 3)) :
    ∀ p ∈ Finset.Icc 1 B, p.Prime →
      ∃ P ∈ primesOver (span {(p : ℤ)}) (𝓞 K23),
        B < p ^ P.inertiaDeg ℤ ∨ Submodule.IsPrincipal (P ^ 3) := by
  intro p hp hpprime
  rcases eq_or_ne p 2 with rfl | hp2
  · exact ⟨BealRegular.TwentyThreePrimeTwoCube.primeIdealTwo,
      BealRegular.TwentyThreePrimeTwoCube.primeIdealTwo_mem_primesOver,
      Or.inr BealRegular.TwentyThreePrimeTwoCube.primeIdealTwo_cube_isPrincipal⟩
  rcases eq_or_ne p 3 with rfl | hp3
  · obtain ⟨P, hP, hPcube⟩ :=
      BealRegular.TwentyThreePrimeThreeCube.exists_prime_above_three_cube_isPrincipal
    exact ⟨P, hP, Or.inr hPcube⟩
  rcases eq_or_ne p 23 with rfl | hp23
  · obtain ⟨P, hP, hPcube⟩ :=
      exists_prime_above_twentyThree_cube_isPrincipal
    exact ⟨P, hP, Or.inr hPcube⟩
  exact h p hp hpprime hp2 hp3 hp23

end

end BealRegular.TwentyThreeRamifiedPrime
