module

public import BealRegular.TwentyThreeRealCertificateBase

/-!
This file is generated by `render_23_real_certificates.mjs` from
`certificates_23_real.json`.  Corpus SHA-256:
`21e554a6a6a2b0d78efef741813a98d5269feebdbf11f9219bb6f8c03d6cc9e7`.
Do not edit this file by hand.
-/

@[expose] public section

open Ideal NumberField Polynomial RingOfIntegers

namespace BealRegular.TwentyThreeRealCertificates.Q139

open BealRegular.PrincipalIdealCertificate
open BealRegular.TwentyThreeRealCertificateBase

noncomputable section

local instance : Fact (Nat.Prime 139) := ⟨by norm_num⟩

def P : ℤ[X] := X + C 3

def Q : ℤ[X] := X ^ 10 - C 4 * X ^ 9 + C 2 * X ^ 8 + C 3 * X ^ 7 + C 27 * X ^ 6 - C 109 * X ^ 5
  + C 271 * X ^ 4 - C 778 * X ^ 3 + C 2369 * X ^ 2 - C 7122 * X + C 21360

def A : ℤ[X] := -C 461

def G : ℤ[X] := -X ^ 10 + X ^ 9 + C 10 * X ^ 8 - C 8 * X ^ 7 - C 36 * X ^ 6 + C 21 * X ^ 5
  + C 55 * X ^ 4 - C 21 * X ^ 3 - C 30 * X ^ 2 + C 7 * X + C 2

def Qq : ℤ[X] := -C 23 * X ^ 10 - C 47 * X ^ 9 + C 232 * X ^ 8 + C 348 * X ^ 7 - C 899 * X ^ 6
  - C 829 * X ^ 5 + C 1551 * X ^ 4 + C 658 * X ^ 3 - C 972 * X ^ 2 - C 75 * X + C 85

def Rq : ℤ[X] := -C 23 * X ^ 9 - C 47 * X ^ 8 + C 232 * X ^ 7 + C 371 * X ^ 6 - C 829 * X ^ 5
  - C 922 * X ^ 4 + C 1251 * X ^ 3 + C 768 * X ^ 2 - C 631 * X - C 31

def QP : ℤ[X] := -X ^ 10 - X ^ 9 + C 9 * X ^ 8 + C 7 * X ^ 7 - C 30 * X ^ 6 - C 16 * X ^ 5
  + C 44 * X ^ 4 + C 13 * X ^ 3 - C 24 * X ^ 2 - C 2 * X + C 2

def RP : ℤ[X] := -X ^ 9 - X ^ 8 + C 9 * X ^ 7 + C 8 * X ^ 6 - C 28 * X ^ 5 - C 20 * X ^ 4
  + C 36 * X ^ 3 + C 17 * X ^ 2 - C 15 * X - C 1

def C1 : ℤ[X] := -X ^ 9 + C 4 * X ^ 8 - C 2 * X ^ 7 - C 2 * X ^ 6 - C 30 * X ^ 5 + C 111 * X ^ 4
  - C 278 * X ^ 3 + C 813 * X ^ 2 - C 2469 * X + C 7414

def C2 : ℤ[X] := -C 160

set_option maxHeartbeats 0 in
-- Exact normalization of the displayed polynomial identity can be expensive.
set_option maxRecDepth 12000 in
/-- The factor identity in ℤ[X]. -/
theorem factorization_identity :
    P * Q + C (139 : ℤ) * A = Phi := by
  simp only [P, Q, A, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  ring

set_option maxHeartbeats 0 in
-- Exact normalization of the three displayed Bezout identities can be expensive.
set_option maxRecDepth 12000 in
/-- The three exact Bezout identities certifying the Kummer--Dedekind ideal. -/
theorem principal_identities :
    C (139 : ℤ) = G * Qq + Phi * Rq ∧
      P = G * QP + Phi * RP ∧
        G = C2 * C (139 : ℤ) + C1 * P + Phi * 0 := by
  simp only [P, G, Qq, Rq, QP, RP, C1, C2, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  constructor
  · ring
  constructor <;> ring

theorem P_monic : P.Monic := by
  simp only [P]
  monicity!

theorem map_P_irreducible :
    Irreducible (P.map (Int.castRingHom (ZMod 139))) := by
  apply Polynomial.irreducible_of_degree_eq_one
  simp only [P, Polynomial.map_add, map_X, map_C]
  compute_degree!

theorem map_P_dvd_Phi :
    P.map (Int.castRingHom (ZMod 139)) ∣
      Phi.map (Int.castRingHom (ZMod 139)) := by
  refine ⟨Q.map (Int.castRingHom (ZMod 139)), ?_⟩
  have h := congrArg (Polynomial.map (Int.castRingHom (ZMod 139)))
    factorization_identity
  simp only [Polynomial.map_add, Polynomial.map_mul, map_C] at h
  have hq : Int.castRingHom (ZMod 139) (139 : ℤ) = 0 := by decide
  rw [hq, C_0, zero_mul, add_zero] at h
  exact h.symm

theorem map_P_mem_monicFactorsMod :
    P.map (Int.castRingHom (ZMod 139)) ∈ monicFactorsMod theta 139 := by
  rw [Multiset.mem_toFinset, Polynomial.mem_normalizedFactors_iff
    (map_monic_ne_zero (minpoly.monic theta.isIntegral))]
  refine ⟨map_P_irreducible, P_monic.map _, ?_⟩
  rw [← Phi_eq_minpoly]
  exact map_P_dvd_Phi

theorem q_not_dvd_exponent : ¬ 139 ∣ exponent theta := by
  rw [theta_exponent]
  norm_num

/-- The prime above 139 selected by the displayed linear factor. -/
noncomputable def selectedPrime :
    primesOver (span {(139 : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  (NumberField.Ideal.primesOverSpanEquivMonicFactorsMod q_not_dvd_exponent).symm
    ⟨P.map (Int.castRingHom (ZMod 139)), map_P_mem_monicFactorsMod⟩

theorem selectedPrime_mem_primesOver :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) ∈
      primesOver (span {(139 : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  selectedPrime.property

theorem selectedPrime_eq_span :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) =
      span {algebraMap ℤ (NumberField.RingOfIntegers RealField) 139, aeval theta P} := by
  exact NumberField.Ideal.primesOverSpanEquivMonicFactorsMod_symm_apply_eq_span
    q_not_dvd_exponent map_P_mem_monicFactorsMod

/-- The selected prime above 139 is principal, with generator G(theta). -/
theorem selectedPrime_isPrincipal :
    Submodule.IsPrincipal
      (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) := by
  rcases principal_identities with ⟨hq, hP, hG⟩
  exact kummerDedekindPrime_isPrincipal_of_polynomial_certificate
    (F := P) (G := G) (Phi := Phi) (QA := Qq) (QB := QP)
    (RA := Rq) (RB := RP) (RG := 0) (CA := C2) (CB := C1)
    (p := 139) theta q_not_dvd_exponent map_P_mem_monicFactorsMod
    aeval_Phi_theta hq hP hG

/-- The exact branch shape consumed by the real-subfield Minkowski criterion. -/
theorem minkowski_branch :
    ∃ J ∈ primesOver (span {(139 : ℤ)})
        (NumberField.RingOfIntegers RealField),
      900 < 139 ^ J.inertiaDeg ℤ ∨ Submodule.IsPrincipal J :=
  ⟨selectedPrime, selectedPrime.property, Or.inr selectedPrime_isPrincipal⟩

end

end BealRegular.TwentyThreeRealCertificates.Q139
