module

public import BealRegular.TwentyThreeRealSubfield
import Mathlib.RingTheory.PowerBasis
import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# The Hasse unit index of Q(zeta_23)

For the CM field `K = ℚ(ζ₂₃)`, the Hasse unit index is the index of the
subgroup generated by its real units and roots of unity.  Mathlib proves that
this index is either one or two, and characterizes the value two by the
existence of a unit `u` for which `u / conj(u)` generates every root of unity.

Reduction modulo the ramified prime `(ζ₂₃ - 1)` rules out that possibility.
The integral power basis generated by `ζ₂₃ - 1` shows that complex conjugation
acts trivially in the residue field.  Thus every `u / conj(u)` reduces to one.
If such an element generated all roots of unity, then `-1` would also reduce
to one, forcing `2` into `(ζ₂₃ - 1)`, contrary to `2 < 23`.
-/

@[expose] public section

open Ideal NumberField NumberField.Units Polynomial

namespace BealRegular.TwentyThreeHasseUnitIndex

open BealRegular.TwentyThreeRamifiedPrime
open BealRegular.TwentyThreeRealSubfield

noncomputable section

local notation "K23" => CyclotomicField 23 ℚ

local instance : Fact (Nat.Prime 23) := ⟨by norm_num⟩
local instance : IsCyclotomicExtension {23} ℚ K23 :=
  CyclotomicField.instIsCyclotomicExtensionSingletonNatSetOfCharZero 23 ℚ
local instance : NumberField.IsCMField K23 :=
  cyclotomicFieldTwentyThree_isCMField

/-- An algebra automorphism preserving the ideal generated by a power-basis
generator acts trivially modulo that ideal. -/
private theorem powerBasis_algEquiv_sub_mem_span_gen
    {R A : Type*} [CommRing R] [CommRing A] [Algebra R A]
    (pb : PowerBasis R A) (σ : A ≃ₐ[R] A)
    (hσ : σ pb.gen ∈ Ideal.span ({pb.gen} : Set A)) (x : A) :
    σ x - x ∈ Ideal.span ({pb.gen} : Set A) := by
  let P : Ideal A := Ideal.span ({pb.gen} : Set A)
  obtain ⟨f, rfl⟩ := pb.exists_eq_aeval' x
  rw [← Ideal.Quotient.eq_zero_iff_mem]
  change Ideal.Quotient.mk P (σ (aeval pb.gen f) - aeval pb.gen f) = 0
  rw [map_sub]
  have hgen : Ideal.Quotient.mk P pb.gen = 0 := by
    rw [Ideal.Quotient.eq_zero_iff_mem]
    exact Ideal.subset_span (Set.mem_singleton pb.gen)
  have hsgen : Ideal.Quotient.mk P (σ pb.gen) = 0 := by
    rw [Ideal.Quotient.eq_zero_iff_mem]
    exact hσ
  simp only [aeval_def]
  change Ideal.Quotient.mk P
      (σ.toRingHom (eval₂ (algebraMap R A) pb.gen f)) -
    Ideal.Quotient.mk P (eval₂ (algebraMap R A) pb.gen f) = 0
  rw [Polynomial.hom_eval₂ f (algebraMap R A) σ.toRingHom pb.gen]
  rw [Polynomial.hom_eval₂, Polynomial.hom_eval₂]
  have hsgen' : Ideal.Quotient.mk P (σ.toRingHom pb.gen) = 0 := hsgen
  have hcoeff :
      (Ideal.Quotient.mk P).comp (σ.toRingHom.comp (algebraMap R A)) =
        (Ideal.Quotient.mk P).comp (algebraMap R A) := by
    ext r
    simp
  rw [hgen, hsgen', hcoeff]
  ring

private noncomputable def ringComplexConj : (𝓞 K23) ≃+* (𝓞 K23) :=
  RingOfIntegers.mapRingEquiv
    (NumberField.IsCMField.complexConj K23).toRingEquiv

private noncomputable def ringComplexConjAlg : (𝓞 K23) ≃ₐ[ℤ] (𝓞 K23) :=
  AlgEquiv.ofRingEquiv (f := ringComplexConj) (by
    intro z
    apply RingOfIntegers.ext
    simp [ringComplexConj])

@[simp]
private theorem ringComplexConjAlg_apply (x : 𝓞 K23) :
    ringComplexConjAlg x = ringComplexConj x := rfl

private theorem ringComplexConj_generator_mem :
    ringComplexConjAlg ramifiedGenerator ∈
      Ideal.span ({ramifiedGenerator} : Set (𝓞 K23)) := by
  rw [ramifiedGenerator]
  rw [Ideal.mem_span_singleton]
  exact (zeta23_spec.toInteger_isPrimitiveRoot.associated_sub_one_map_sub_one
    ringComplexConjAlg).dvd

private theorem ringComplexConj_sub_mem (x : 𝓞 K23) :
    ringComplexConjAlg x - x ∈
      Ideal.span ({ramifiedGenerator} : Set (𝓞 K23)) := by
  let pb := zeta23_spec.subOneIntegralPowerBasis
  have hgen : pb.gen = ramifiedGenerator := by
    change zeta23_spec.subOneIntegralPowerBasis.gen = ramifiedGenerator
    rw [zeta23_spec.subOneIntegralPowerBasis_gen]
    apply RingOfIntegers.ext
    change IsCyclotomicExtension.zeta 23 ℚ K23 - 1 =
      IsCyclotomicExtension.zeta 23 ℚ K23 - 1
    rfl
  rw [← hgen]
  exact powerBasis_algEquiv_sub_mem_span_gen pb ringComplexConjAlg
    (by simpa only [hgen] using ringComplexConj_generator_mem) x

private theorem unitRatio_sub_one_mem (u : (𝓞 K23)ˣ) :
    (((NumberField.IsCMField.unitsMulComplexConjInv K23 u :
        NumberField.Units.torsion K23) : (𝓞 K23)ˣ) : 𝓞 K23) - 1 ∈
      Ideal.span ({ramifiedGenerator} : Set (𝓞 K23)) := by
  rw [NumberField.IsCMField.unitsMulComplexConjInv_apply]
  change ((u : 𝓞 K23) *
      (((NumberField.IsCMField.unitsComplexConj K23 u)⁻¹ : (𝓞 K23)ˣ) : 𝓞 K23) - 1) ∈
    Ideal.span ({ramifiedGenerator} : Set (𝓞 K23))
  have hconj : ringComplexConjAlg (u : 𝓞 K23) =
      ((NumberField.IsCMField.unitsComplexConj K23 u : (𝓞 K23)ˣ) : 𝓞 K23) := by
    apply RingOfIntegers.ext
    rfl
  have hprod : ringComplexConjAlg (u : 𝓞 K23) *
      (((NumberField.IsCMField.unitsComplexConj K23 u)⁻¹ : (𝓞 K23)ˣ) : 𝓞 K23) = 1 := by
    rw [hconj]
    change (((NumberField.IsCMField.unitsComplexConj K23 u) *
      (NumberField.IsCMField.unitsComplexConj K23 u)⁻¹ : (𝓞 K23)ˣ) : 𝓞 K23) = 1
    simp
  rw [show (u : 𝓞 K23) *
        (((NumberField.IsCMField.unitsComplexConj K23 u)⁻¹ : (𝓞 K23)ˣ) : 𝓞 K23) - 1 =
      ((u : 𝓞 K23) - ringComplexConjAlg (u : 𝓞 K23)) *
        (((NumberField.IsCMField.unitsComplexConj K23 u)⁻¹ : (𝓞 K23)ˣ) : 𝓞 K23) by
    rw [sub_mul]
    rw [hprod]]
  exact Ideal.mul_mem_right _ _
    (by
      have h := Submodule.neg_mem _ (ringComplexConj_sub_mem (u : 𝓞 K23))
      simpa only [neg_sub] using h)

private theorem unitRatio_does_not_generate_torsion (u : (𝓞 K23)ˣ) :
    Subgroup.zpowers (NumberField.IsCMField.unitsMulComplexConjInv K23 u) ≠ ⊤ := by
  intro htop
  let w : NumberField.Units.torsion K23 :=
    NumberField.IsCMField.unitsMulComplexConjInv K23 u
  let minusOne : NumberField.Units.torsion K23 :=
    ⟨-1, neg_one_mem_torsion⟩
  have hminus_mem : minusOne ∈ Subgroup.zpowers w := by
    rw [htop]
    exact Subgroup.mem_top minusOne
  obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp hminus_mem
  let J : Ideal (𝓞 K23) := Ideal.span ({ramifiedGenerator} : Set (𝓞 K23))
  let q : (𝓞 K23) →+* ((𝓞 K23) ⧸ J) := Ideal.Quotient.mk J
  have hwmap : Units.map q.toMonoidHom (w : (𝓞 K23)ˣ) = 1 := by
    apply Units.ext
    change q ((w : (𝓞 K23)ˣ) : 𝓞 K23) = 1
    rw [← sub_eq_zero]
    apply Ideal.Quotient.eq_zero_iff_mem.mpr
    simpa only [J, w] using unitRatio_sub_one_mem u
  have hminus_map : Units.map q.toMonoidHom (minusOne : (𝓞 K23)ˣ) = 1 := by
    calc
      Units.map q.toMonoidHom (minusOne : (𝓞 K23)ˣ) =
          Units.map q.toMonoidHom ((w ^ n : NumberField.Units.torsion K23) : (𝓞 K23)ˣ) := by
            rw [hn]
      _ = (Units.map q.toMonoidHom (w : (𝓞 K23)ˣ)) ^ n := by simp
      _ = 1 := by rw [hwmap]; simp
  have hneg : (-1 : (𝓞 K23) ⧸ J) = 1 := by
    have h := congrArg (fun z : ((𝓞 K23) ⧸ J)ˣ => (z : (𝓞 K23) ⧸ J)) hminus_map
    have hqneg : q.toMonoidHom (-1 : 𝓞 K23) = 1 := by
      simpa only [minusOne, Units.coe_map, Units.val_neg, Units.val_one] using h
    calc
      (-1 : (𝓞 K23) ⧸ J) = q.toMonoidHom (-1 : 𝓞 K23) := by
        change (-1 : (𝓞 K23) ⧸ J) = q (-1 : 𝓞 K23)
        simp only [map_neg, map_one]
      _ = 1 := hqneg
  have htwo_zero : q (2 : 𝓞 K23) = 0 := by
    change (2 : (𝓞 K23) ⧸ J) = 0
    calc
      (2 : (𝓞 K23) ⧸ J) = 1 - (-1) := by ring
      _ = 1 - 1 := by rw [hneg]
      _ = 0 := sub_self 1
  have htwo_mem : (2 : 𝓞 K23) ∈ J :=
    Ideal.Quotient.eq_zero_iff_mem.mp htwo_zero
  exact (IsCyclotomicExtension.Rat.two_not_mem_span_zeta_sub_one' 23 zeta23_spec (by norm_num))
    (by simpa only [J, ramifiedGenerator] using htwo_mem)

/-- The Hasse unit index of the 23rd cyclotomic field is one.  Equivalently,
its units are generated by units from the maximal real subfield together with
the roots of unity. -/
theorem indexRealUnits_eq_one :
    NumberField.IsCMField.indexRealUnits K23 = 1 := by
  rcases NumberField.IsCMField.indexRealUnits_eq_one_or_two K23 with h | h
  · exact h
  · obtain ⟨u, hu⟩ :=
      (NumberField.IsCMField.indexRealUnits_eq_two_iff K23).mp h
    exact (unitRatio_does_not_generate_torsion u hu).elim

end

end BealRegular.TwentyThreeHasseUnitIndex
