module

public import BealRegular.TwentyThreeRealCertificateBase

/-!
This file is generated by `render_23_real_certificates.mjs` from
`certificates_23_real.json`.  Corpus SHA-256:
`21e554a6a6a2b0d78efef741813a98d5269feebdbf11f9219bb6f8c03d6cc9e7`.
Do not edit this file by hand.
-/

@[expose] public section

open Ideal NumberField Polynomial RingOfIntegers

namespace BealRegular.TwentyThreeRealCertificates.Q47

open BealRegular.PrincipalIdealCertificate
open BealRegular.TwentyThreeRealCertificateBase

noncomputable section

local instance : Fact (Nat.Prime 47) := ⟨by norm_num⟩

def P : ℤ[X] := X + C 4

def Q : ℤ[X] := X ^ 10 - C 5 * X ^ 9 + C 10 * X ^ 8 - C 31 * X ^ 7 + C 160 * X ^ 6 - C 668 * X ^ 5
  + C 2616 * X ^ 4 - C 10429 * X ^ 3 + C 41751 * X ^ 2 - C 167019 * X + C 668070

def A : ℤ[X] := -C 56857

def G : ℤ[X] := -X ^ 9 + X ^ 8 + C 9 * X ^ 7 - C 7 * X ^ 6 - C 27 * X ^ 5 + C 15 * X ^ 4
  + C 30 * X ^ 3 - C 10 * X ^ 2 - C 9 * X + C 1

def Qq : ℤ[X] := C 7 * X ^ 10 - C 35 * X ^ 9 - C 71 * X ^ 8 + C 300 * X ^ 7 + C 274 * X ^ 6
  - C 869 * X ^ 5 - C 488 * X ^ 4 + C 975 * X ^ 3 + C 387 * X ^ 2 - C 337 * X - C 104

def Rq : ℤ[X] := C 7 * X ^ 8 - C 35 * X ^ 7 - C 64 * X ^ 6 + C 258 * X ^ 5 + C 238 * X ^ 4
  - C 540 * X ^ 3 - C 353 * X ^ 2 + C 307 * X + C 151

def QP : ℤ[X] := -C 3 * X ^ 9 - X ^ 8 + C 26 * X ^ 7 + C 9 * X ^ 6 - C 76 * X ^ 5 - C 26 * X ^ 4
  + C 86 * X ^ 3 + C 28 * X ^ 2 - C 30 * X - C 9

def RP : ℤ[X] := -C 3 * X ^ 7 - X ^ 6 + C 23 * X ^ 5 + C 11 * X ^ 4 - C 49 * X ^ 3 - C 25 * X ^ 2
  + C 28 * X + C 13

def C1 : ℤ[X] := -X ^ 8 + C 5 * X ^ 7 - C 11 * X ^ 6 + C 37 * X ^ 5 - C 175 * X ^ 4 + C 715 * X ^ 3
  - C 2830 * X ^ 2 + C 11310 * X - C 45249

def C2 : ℤ[X] := C 3851

set_option maxHeartbeats 0 in
-- Exact normalization of the displayed polynomial identity can be expensive.
set_option maxRecDepth 12000 in
/-- The factor identity in ℤ[X]. -/
theorem factorization_identity :
    P * Q + C (47 : ℤ) * A = Phi := by
  simp only [P, Q, A, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  ring

set_option maxHeartbeats 0 in
-- Exact normalization of the three displayed Bezout identities can be expensive.
set_option maxRecDepth 12000 in
/-- The three exact Bezout identities certifying the Kummer--Dedekind ideal. -/
theorem principal_identities :
    C (47 : ℤ) = G * Qq + Phi * Rq ∧
      P = G * QP + Phi * RP ∧
        G = C2 * C (47 : ℤ) + C1 * P + Phi * 0 := by
  simp only [P, G, Qq, Rq, QP, RP, C1, C2, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  constructor
  · ring
  constructor <;> ring

theorem P_monic : P.Monic := by
  simp only [P]
  monicity!

theorem map_P_irreducible :
    Irreducible (P.map (Int.castRingHom (ZMod 47))) := by
  apply Polynomial.irreducible_of_degree_eq_one
  simp only [P, Polynomial.map_add, map_X, map_C]
  compute_degree!

theorem map_P_dvd_Phi :
    P.map (Int.castRingHom (ZMod 47)) ∣
      Phi.map (Int.castRingHom (ZMod 47)) := by
  refine ⟨Q.map (Int.castRingHom (ZMod 47)), ?_⟩
  have h := congrArg (Polynomial.map (Int.castRingHom (ZMod 47)))
    factorization_identity
  simp only [Polynomial.map_add, Polynomial.map_mul, map_C] at h
  have hq : Int.castRingHom (ZMod 47) (47 : ℤ) = 0 := by decide
  rw [hq, C_0, zero_mul, add_zero] at h
  exact h.symm

theorem map_P_mem_monicFactorsMod :
    P.map (Int.castRingHom (ZMod 47)) ∈ monicFactorsMod theta 47 := by
  rw [Multiset.mem_toFinset, Polynomial.mem_normalizedFactors_iff
    (map_monic_ne_zero (minpoly.monic theta.isIntegral))]
  refine ⟨map_P_irreducible, P_monic.map _, ?_⟩
  rw [← Phi_eq_minpoly]
  exact map_P_dvd_Phi

theorem q_not_dvd_exponent : ¬ 47 ∣ exponent theta := by
  rw [theta_exponent]
  norm_num

/-- The prime above 47 selected by the displayed linear factor. -/
noncomputable def selectedPrime :
    primesOver (span {(47 : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  (NumberField.Ideal.primesOverSpanEquivMonicFactorsMod q_not_dvd_exponent).symm
    ⟨P.map (Int.castRingHom (ZMod 47)), map_P_mem_monicFactorsMod⟩

theorem selectedPrime_mem_primesOver :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) ∈
      primesOver (span {(47 : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  selectedPrime.property

theorem selectedPrime_eq_span :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) =
      span {algebraMap ℤ (NumberField.RingOfIntegers RealField) 47, aeval theta P} := by
  exact NumberField.Ideal.primesOverSpanEquivMonicFactorsMod_symm_apply_eq_span
    q_not_dvd_exponent map_P_mem_monicFactorsMod

/-- The selected prime above 47 is principal, with generator G(theta). -/
theorem selectedPrime_isPrincipal :
    Submodule.IsPrincipal
      (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) := by
  rcases principal_identities with ⟨hq, hP, hG⟩
  exact kummerDedekindPrime_isPrincipal_of_polynomial_certificate
    (F := P) (G := G) (Phi := Phi) (QA := Qq) (QB := QP)
    (RA := Rq) (RB := RP) (RG := 0) (CA := C2) (CB := C1)
    (p := 47) theta q_not_dvd_exponent map_P_mem_monicFactorsMod
    aeval_Phi_theta hq hP hG

/-- The exact branch shape consumed by the real-subfield Minkowski criterion. -/
theorem minkowski_branch :
    ∃ J ∈ primesOver (span {(47 : ℤ)})
        (NumberField.RingOfIntegers RealField),
      900 < 47 ^ J.inertiaDeg ℤ ∨ Submodule.IsPrincipal J :=
  ⟨selectedPrime, selectedPrime.property, Or.inr selectedPrime_isPrincipal⟩

end

end BealRegular.TwentyThreeRealCertificates.Q47
