import BealRegular.TwentyThreeRealSubfieldPowerBasis

#print axioms BealRegular.TwentyThreeRealSubfieldPowerBasis.alpha_isIntegral_rat
#print axioms BealRegular.TwentyThreeRealSubfieldPowerBasis.alpha_isIntegral_int
#print axioms BealRegular.TwentyThreeRealSubfieldPowerBasis.realSubfieldPolynomial_eq_minpoly_int_alpha
#print axioms BealRegular.TwentyThreeRealSubfieldPowerBasis.algebra_adjoin_alpha_eq_top
#print axioms BealRegular.TwentyThreeRealSubfieldPowerBasis.alphaPowerBasis_gen
#print axioms BealRegular.TwentyThreeRealSubfieldPowerBasis.alphaPowerBasis_dim
#print axioms BealRegular.TwentyThreeRealSubfieldPowerBasis.alphaPowerBasis_minpoly
#print axioms BealRegular.TwentyThreeRealSubfieldPowerBasis.beta_isIntegral_int
#print axioms BealRegular.TwentyThreeRealSubfieldPowerBasis.beta_isIntegral_rat
#print axioms BealRegular.TwentyThreeRealSubfieldPowerBasis.minpoly_int_beta_eq_shiftedRealSubfieldPolynomial
#print axioms BealRegular.TwentyThreeRealSubfieldPowerBasis.minpoly_rat_beta_eq_shiftedRealSubfieldPolynomial_map
#print axioms BealRegular.TwentyThreeRealSubfieldPowerBasis.minpoly_beta_natDegree
#print axioms BealRegular.TwentyThreeRealSubfieldPowerBasis.beta_adjoin_eq_top
#print axioms BealRegular.TwentyThreeRealSubfieldPowerBasis.algebra_adjoin_beta_eq_top
#print axioms BealRegular.TwentyThreeRealSubfieldPowerBasis.betaPowerBasis_gen
#print axioms BealRegular.TwentyThreeRealSubfieldPowerBasis.betaPowerBasis_dim
#print axioms BealRegular.TwentyThreeRealSubfieldPowerBasis.betaPowerBasis_minpoly_int
#print axioms BealRegular.TwentyThreeRealSubfieldPowerBasis.betaPowerBasis_minpoly_rat
#print axioms BealRegular.TwentyThreeRealSubfieldPowerBasis.norm_aeval_eq_resultant
#print axioms BealRegular.TwentyThreeRealSubfieldPowerBasis.alphaPowerBasis_discr_eq_polynomial_discr
#print axioms BealRegular.TwentyThreeRealSubfieldPowerBasis.betaPowerBasis_discr_eq_polynomial_discr
#print axioms BealRegular.TwentyThreeRealSubfieldPowerBasis.smul_pow_twentyThree
#print axioms BealRegular.TwentyThreeRealSubfieldPowerBasis.isIntegralClosure_adjoin_beta_of_discr
