module

public import BealRegular.TwentyThreeRealSubfieldPowerBasis

/-!
# The discriminant and maximal order of the real subfield at 23

An explicit Euclidean resultant chain computes the discriminant of the
degree-eleven real-subfield polynomial as `23^10`.  Combining this with the
power basis generated by `alpha` and the 23-Eisenstein translate `beta`
proves that `ℤ[beta]` is the full integral closure.
-/

@[expose] public section

namespace BealRegular.TwentyThreeRealSubfieldDiscriminant

open BealRegular.TwentyThreeRealSubfield
open BealRegular.TwentyThreeRealSubfieldEisenstein
open BealRegular.TwentyThreeRealSubfieldPowerBasis
open Polynomial

noncomputable section

local notation "K23" => CyclotomicField 23 ℚ
local notation "K23plus" => NumberField.maximalRealSubfield K23

private lemma mul_C_eq_smul (p : ℚ[X]) (a : ℚ) :
    p * C a = a • p := by
  rw [mul_comm]
  exact (Polynomial.qsmul_eq_C_mul a p).symm

private lemma C_mul_eq_smul (p : ℚ[X]) (a : ℚ) :
    C a * p = a • p :=
  (Polynomial.qsmul_eq_C_mul a p).symm

private lemma C_eq_smul_one (a : ℚ) :
    C a = a • (1 : ℚ[X]) := by
  rw [← Polynomial.C_1, Polynomial.smul_C]
  simp

/-- One step of the normalized polynomial remainder sequence used below. -/
private lemma resultant_step
    {f g h q : ℚ[X]} {n : ℕ} {c : ℚ}
    (hn : 0 < n)
    (hf : f.natDegree = n + 1)
    (hg : g.natDegree = n)
    (hh : h.natDegree = n - 1)
    (hgm : g.Monic)
    (hc : c ≠ 0)
    (hq : q.natDegree ≤ 1)
    (heq : f = C c * h + g * q) :
    f.resultant g = c ^ n * g.resultant h := by
  have hch : (C c * h).natDegree = n - 1 := by
    rw [natDegree_C_mul hc, hh]
  have hqdeg : q.natDegree + n ≤ n + 1 := by omega
  rw [show f.resultant g = f.resultant g (n + 1) n by simp [hf, hg]]
  rw [heq]
  rw [resultant_add_mul_left _ _ _ _ _ hqdeg (by simp [hg])]
  rw [show n + 1 = (n - 1) + 2 by omega]
  rw [resultant_add_left_deg (C c * h) g (n - 1) n 2 hch.le]
  rw [show g.coeff n = 1 by rw [← hg, hgm.coeff_natDegree]]
  simp only [one_pow, mul_one]
  rw [resultant_comm]
  rw [resultant_C_mul_right]
  simp only [hg, hh]
  have heven1 : Even (n * 2) := ⟨n, by omega⟩
  have heven2 : Even ((n - 1) * n) := by
    simpa [mul_comm] using Nat.even_mul_pred_self n
  rw [heven1.neg_one_pow, heven2.neg_one_pow]
  simp

private def p11 : ℚ[X] :=
  X ^ 11 + C (-1) * X ^ 10 + C (-10) * X ^ 9 + C 9 * X ^ 8 +
    C 36 * X ^ 7 + C (-28) * X ^ 6 + C (-56) * X ^ 5 + C 35 * X ^ 4 +
      C 35 * X ^ 3 + C (-15) * X ^ 2 + C (-6) * X + C 1

private def p10 : ℚ[X] :=
  X ^ 10 + C (-10 / 11) * X ^ 9 + C (-90 / 11) * X ^ 8 +
    C (72 / 11) * X ^ 7 + C (252 / 11) * X ^ 6 + C (-168 / 11) * X ^ 5 +
      C (-280 / 11) * X ^ 4 + C (140 / 11) * X ^ 3 + C (105 / 11) * X ^ 2 +
        C (-30 / 11) * X + C (-6 / 11)

private def p9 : ℚ[X] :=
  X ^ 9 + C (-9 / 10) * X ^ 8 + C (-36 / 5) * X ^ 7 +
    C (28 / 5) * X ^ 6 + C (84 / 5) * X ^ 5 + C (-21 / 2) * X ^ 4 +
      C (-14) * X ^ 3 + C 6 * X ^ 2 + C 3 * X + C (-1 / 2)

private def p8 : ℚ[X] :=
  X ^ 8 + C (-8 / 9) * X ^ 7 + C (-56 / 9) * X ^ 6 +
    C (14 / 3) * X ^ 5 + C (35 / 3) * X ^ 4 + C (-20 / 3) * X ^ 3 +
      C (-20 / 3) * X ^ 2 + C (20 / 9) * X + C (5 / 9)

private def p7 : ℚ[X] :=
  X ^ 7 + C (-7 / 8) * X ^ 6 + C (-21 / 4) * X ^ 5 +
    C (15 / 4) * X ^ 4 + C (15 / 2) * X ^ 3 + C (-15 / 4) * X ^ 2 +
      C (-5 / 2) * X + C (1 / 2)

private def p6 : ℚ[X] :=
  X ^ 6 + C (-6 / 7) * X ^ 5 + C (-30 / 7) * X ^ 4 +
    C (20 / 7) * X ^ 3 + C (30 / 7) * X ^ 2 + C (-12 / 7) * X + C (-4 / 7)

private def p5 : ℚ[X] :=
  X ^ 5 + C (-5 / 6) * X ^ 4 + C (-10 / 3) * X ^ 3 +
    C 2 * X ^ 2 + C 2 * X + C (-1 / 2)

private def p4 : ℚ[X] :=
  X ^ 4 + C (-4 / 5) * X ^ 3 + C (-12 / 5) * X ^ 2 +
    C (6 / 5) * X + C (3 / 5)

private def p3 : ℚ[X] :=
  X ^ 3 + C (-3 / 4) * X ^ 2 + C (-3 / 2) * X + C (1 / 2)

private def p2 : ℚ[X] :=
  X ^ 2 + C (-2 / 3) * X + C (-2 / 3)

private def p1 : ℚ[X] := X + C (-1 / 2)

private def p0 : ℚ[X] := 1

private lemma res11_10 :
    p11.resultant p10 = (-230 / 121 : ℚ) ^ 10 * p10.resultant p9 := by
  apply resultant_step (n := 10) (q := X - C (1 / 11))
  · norm_num
  · simp only [p11]
    compute_degree!
  · simp only [p10]
    compute_degree!
  · simp only [p9]
    compute_degree!
  · simp only [p10]
    monicity!
  · norm_num
  · compute_degree!
  · simp [p11, p10, p9]
    ring_nf
    simp only [mul_C_eq_smul]
    simp only [C_eq_smul_one]
    module

private lemma res10_9 :
    p10.resultant p9 = (-99 / 100 : ℚ) ^ 9 * p9.resultant p8 := by
  apply resultant_step (n := 9) (q := X - C (1 / 110))
  · norm_num
  · simp only [p10]
    compute_degree!
  · simp only [p9]
    compute_degree!
  · simp only [p8]
    compute_degree!
  · simp only [p9]
    monicity!
  · norm_num
  · compute_degree!
  · simp [p10, p9, p8]
    ring_nf
    simp only [mul_C_eq_smul]
    simp only [C_eq_smul_one]
    module

private lemma res9_8 :
    p9.resultant p8 = (-80 / 81 : ℚ) ^ 8 * p8.resultant p7 := by
  apply resultant_step (n := 8) (q := X - C (1 / 90))
  · norm_num
  · simp only [p9]
    compute_degree!
  · simp only [p8]
    compute_degree!
  · simp only [p7]
    compute_degree!
  · simp only [p8]
    monicity!
  · norm_num
  · compute_degree!
  · simp [p9, p8, p7]
    ring_nf
    simp only [mul_C_eq_smul]
    simp only [C_eq_smul_one]
    module

private lemma res8_7 :
    p8.resultant p7 = (-63 / 64 : ℚ) ^ 7 * p7.resultant p6 := by
  apply resultant_step (n := 7) (q := X - C (1 / 72))
  · norm_num
  · simp only [p8]
    compute_degree!
  · simp only [p7]
    compute_degree!
  · simp only [p6]
    compute_degree!
  · simp only [p7]
    monicity!
  · norm_num
  · compute_degree!
  · simp [p8, p7, p6]
    ring_nf
    simp only [mul_C_eq_smul]
    simp only [C_eq_smul_one]
    module

private lemma res7_6 :
    p7.resultant p6 = (-48 / 49 : ℚ) ^ 6 * p6.resultant p5 := by
  apply resultant_step (n := 6) (q := X - C (1 / 56))
  · norm_num
  · simp only [p7]
    compute_degree!
  · simp only [p6]
    compute_degree!
  · simp only [p5]
    compute_degree!
  · simp only [p6]
    monicity!
  · norm_num
  · compute_degree!
  · simp [p7, p6, p5]
    ring_nf
    simp only [mul_C_eq_smul]
    simp only [C_eq_smul_one]
    module

private lemma res6_5 :
    p6.resultant p5 = (-35 / 36 : ℚ) ^ 5 * p5.resultant p4 := by
  apply resultant_step (n := 5) (q := X - C (1 / 42))
  · norm_num
  · simp only [p6]
    compute_degree!
  · simp only [p5]
    compute_degree!
  · simp only [p4]
    compute_degree!
  · simp only [p5]
    monicity!
  · norm_num
  · compute_degree!
  · simp [p6, p5, p4]
    ring_nf
    simp only [mul_C_eq_smul]
    simp only [C_eq_smul_one]
    module

private lemma res5_4 :
    p5.resultant p4 = (-24 / 25 : ℚ) ^ 4 * p4.resultant p3 := by
  apply resultant_step (n := 4) (q := X - C (1 / 30))
  · norm_num
  · simp only [p5]
    compute_degree!
  · simp only [p4]
    compute_degree!
  · simp only [p3]
    compute_degree!
  · simp only [p4]
    monicity!
  · norm_num
  · compute_degree!
  · simp [p5, p4, p3]
    ring_nf
    simp only [mul_C_eq_smul]
    simp only [C_eq_smul_one]
    module

private lemma res4_3 :
    p4.resultant p3 = (-15 / 16 : ℚ) ^ 3 * p3.resultant p2 := by
  apply resultant_step (n := 3) (q := X - C (1 / 20))
  · norm_num
  · simp only [p4]
    compute_degree!
  · simp only [p3]
    compute_degree!
  · simp only [p2]
    compute_degree!
  · simp only [p3]
    monicity!
  · norm_num
  · compute_degree!
  · simp [p4, p3, p2]
    ring_nf
    simp only [mul_C_eq_smul]
    simp only [C_eq_smul_one]
    module

private lemma res3_2 :
    p3.resultant p2 = (-8 / 9 : ℚ) ^ 2 * p2.resultant p1 := by
  apply resultant_step (n := 2) (q := X - C (1 / 12))
  · norm_num
  · simp only [p3]
    compute_degree!
  · simp only [p2]
    compute_degree!
  · simp only [p1]
    compute_degree!
  · simp only [p2]
    monicity!
  · norm_num
  · compute_degree!
  · simp [p3, p2, p1]
    ring_nf
    simp only [mul_C_eq_smul]
    simp only [C_eq_smul_one]
    module

private lemma res2_1 :
    p2.resultant p1 = (-3 / 4 : ℚ) ^ 1 * p1.resultant p0 := by
  apply resultant_step (n := 1) (q := X - C (1 / 6))
  · norm_num
  · simp only [p2]
    compute_degree!
  · simp only [p1]
    compute_degree!
  · simp only [p0]
    compute_degree!
  · simp only [p1]
    monicity!
  · norm_num
  · compute_degree!
  · simp [p2, p1, p0]
    ring_nf
    simp only [mul_C_eq_smul]
    simp only [C_eq_smul_one]
    module

private lemma resultant_p11_p10 :
    p11.resultant p10 = -(23 : ℚ) ^ 10 / 11 ^ 11 := by
  rw [res11_10, res10_9, res9_8, res8_7, res7_6, res6_5, res5_4,
    res4_3, res3_2, res2_1]
  norm_num [p0]

private lemma p11_eq_realSubfieldPolynomialRat :
    p11 = realSubfieldPolynomialRat := by
  simp [p11, realSubfieldPolynomialRat, realSubfieldPolynomial]
  ring_nf
  simp only [Polynomial.C_ofNat]

private lemma p11_natDegree : p11.natDegree = 11 := by
  simp only [p11]
  compute_degree!

private lemma p10_natDegree : p10.natDegree = 10 := by
  simp only [p10]
  compute_degree!

private lemma p11_monic : p11.Monic := by
  simp only [p11]
  monicity!

private lemma derivative_p11 : p11.derivative = C 11 * p10 := by
  simp [p11, p10]
  ring_nf
  simp only [← Polynomial.C_ofNat]
  simp only [mul_C_eq_smul]
  simp only [C_mul_eq_smul]
  simp only [C_eq_smul_one]
  module

private lemma resultant_p11_derivative :
    p11.resultant p11.derivative = -(23 : ℚ) ^ 10 := by
  rw [derivative_p11]
  rw [show (C (11 : ℚ) * p10).natDegree = 10 by
    rw [natDegree_C_mul (by norm_num), p10_natDegree]]
  rw [resultant_C_mul_right]
  rw [p11_natDegree]
  rw [show p11.resultant p10 11 10 = p11.resultant p10 by
    rw [p11_natDegree, p10_natDegree]]
  rw [resultant_p11_p10]
  norm_num

private lemma discr_p11 : p11.discr = (23 : ℚ) ^ 10 := by
  have hr := Polynomial.resultant_deriv (f := p11) (by
    rw [← natDegree_pos_iff_degree_pos, p11_natDegree]
    norm_num)
  have hderiv : p11.derivative.natDegree = 10 := by
    rw [derivative_p11, natDegree_C_mul (by norm_num), p10_natDegree]
  have hr' : p11.resultant p11.derivative = -p11.discr := by
    rw [show p11.resultant p11.derivative =
        p11.resultant p11.derivative p11.natDegree (p11.natDegree - 1) by
      rw [hderiv, p11_natDegree]]
    rw [hr, p11_natDegree, p11_monic.leadingCoeff]
    norm_num
  have h := resultant_p11_derivative
  rw [hr'] at h
  linarith

/-- The explicit rational real-subfield polynomial has discriminant `23^10`. -/
theorem realSubfieldPolynomialRat_discr :
    realSubfieldPolynomialRat.discr = (23 : ℚ) ^ 10 := by
  rw [← p11_eq_realSubfieldPolynomialRat]
  exact discr_p11

private lemma realSubfieldPolynomial_derivative_natDegree :
    realSubfieldPolynomial.derivative.natDegree = 10 := by
  rw [Polynomial.natDegree_derivative,
    realSubfieldPolynomial_natDegree]

private lemma resultant_realSubfieldPolynomial_derivative :
    realSubfieldPolynomial.resultant realSubfieldPolynomial.derivative =
      -(23 : ℤ) ^ 10 := by
  apply_fun (Int.castRingHom ℚ) using Int.cast_injective
  rw [← Polynomial.resultant_map_map]
  rw [← Polynomial.derivative_map]
  rw [realSubfieldPolynomial_natDegree,
    realSubfieldPolynomial_derivative_natDegree]
  change realSubfieldPolynomialRat.resultant
    realSubfieldPolynomialRat.derivative 11 10 =
      (Int.castRingHom ℚ) (-(23 : ℤ) ^ 10)
  rw [← p11_eq_realSubfieldPolynomialRat]
  rw [show p11.resultant p11.derivative 11 10 =
      p11.resultant p11.derivative by
    rw [p11_natDegree]
    rw [show p11.derivative.natDegree = 10 by
      rw [derivative_p11, natDegree_C_mul (by norm_num),
        p10_natDegree]]]
  rw [resultant_p11_derivative]
  norm_num

/-- The integral real-subfield polynomial has discriminant `23^10`. -/
theorem realSubfieldPolynomial_discr :
    realSubfieldPolynomial.discr = (23 : ℤ) ^ 10 := by
  have hr := Polynomial.resultant_deriv (f := realSubfieldPolynomial) (by
    rw [← natDegree_pos_iff_degree_pos,
      realSubfieldPolynomial_natDegree]
    norm_num)
  have hr' : realSubfieldPolynomial.resultant
      realSubfieldPolynomial.derivative =
      -realSubfieldPolynomial.discr := by
    rw [show realSubfieldPolynomial.resultant
        realSubfieldPolynomial.derivative =
        realSubfieldPolynomial.resultant
          realSubfieldPolynomial.derivative
          realSubfieldPolynomial.natDegree
          (realSubfieldPolynomial.natDegree - 1) by
      rw [realSubfieldPolynomial_derivative_natDegree,
        realSubfieldPolynomial_natDegree]]
    rw [hr, realSubfieldPolynomial_natDegree,
      realSubfieldPolynomial_monic.leadingCoeff]
    norm_num
  have h := resultant_realSubfieldPolynomial_derivative
  rw [hr'] at h
  linarith

/-- The explicit `alpha` power basis has discriminant `23^10`. -/
theorem alphaPowerBasis_discr :
    Algebra.discr ℚ alphaPowerBasis.basis = (23 : ℚ) ^ 10 := by
  rw [alphaPowerBasis_discr_eq_polynomial_discr]
  exact realSubfieldPolynomialRat_discr

/-- Translation by two does not change the integral order generated by the
real-subfield generator. -/
theorem adjoin_int_alpha_eq_adjoin_beta :
    Algebra.adjoin ℤ ({alpha} : Set K23plus) =
      Algebra.adjoin ℤ ({beta} : Set K23plus) := by
  apply le_antisymm
  · apply Algebra.adjoin_le
    intro x hx
    simp only [Set.mem_singleton_iff] at hx
    subst x
    rw [show alpha = beta - algebraMap ℤ K23plus 2 by
      simp [beta]]
    exact Subalgebra.sub_mem _ (Algebra.subset_adjoin (Set.mem_singleton beta))
      (Subalgebra.algebraMap_mem _ 2)
  · apply Algebra.adjoin_le
    intro x hx
    simp only [Set.mem_singleton_iff] at hx
    subst x
    rw [show beta = alpha + algebraMap ℤ K23plus 2 by
      simp [beta]]
    exact Subalgebra.add_mem _ (Algebra.subset_adjoin (Set.mem_singleton alpha))
      (Subalgebra.algebraMap_mem _ 2)

/-- The order generated by the 23-Eisenstein translate `beta` is the full
integral closure of `ℤ` in the maximal real subfield. -/
theorem isIntegralClosure_adjoin_beta :
    IsIntegralClosure (Algebra.adjoin ℤ ({beta} : Set K23plus)) ℤ
      K23plus := by
  refine ⟨Subtype.val_injective,
    @fun x => ⟨fun h => ⟨⟨x, ?_⟩, rfl⟩, ?_⟩⟩
  swap
  · rintro ⟨y, rfl⟩
    exact IsIntegral.algebraMap
      ((le_integralClosure_iff_isIntegral.1
        (adjoin_le_integralClosure beta_isIntegral_int)).isIntegral y)
  · have hintAlpha : IsIntegral ℤ alphaPowerBasis.gen := by
      rw [alphaPowerBasis_gen]
      exact alpha_isIntegral_int
    have H := Algebra.discr_mul_isIntegral_mem_adjoin ℚ hintAlpha h
    rw [alphaPowerBasis_discr] at H
    have Halpha :
        (23 : ℤ) ^ 10 • x ∈
          Algebra.adjoin ℤ ({alpha} : Set K23plus) := by
      rw [← smul_pow_twentyThree, ← alphaPowerBasis_gen]
      exact H
    have Hbeta :
        (23 : ℤ) ^ 10 • x ∈
          Algebra.adjoin ℤ ({betaPowerBasis.gen} : Set K23plus) := by
      rw [betaPowerBasis_gen, ← adjoin_int_alpha_eq_adjoin_beta]
      exact Halpha
    have hintBeta : IsIntegral ℤ betaPowerBasis.gen := by
      rw [betaPowerBasis_gen]
      exact beta_isIntegral_int
    have hmin :
        (minpoly ℤ betaPowerBasis.gen).IsEisensteinAt
          (Submodule.span ℤ {(23 : ℤ)}) := by
      rw [betaPowerBasis_gen,
        minpoly_int_beta_eq_shiftedRealSubfieldPolynomial]
      exact shiftedRealSubfieldPolynomial_isEisensteinAt
    simpa only [betaPowerBasis_gen] using
      (mem_adjoin_of_smul_prime_pow_smul_of_minpoly_isEisensteinAt
        (p := (23 : ℤ)) (n := 10)
        (Nat.prime_iff_prime_int.1
          BealRegular.TwentyThreePrimeTwoCube.prime_twentyThree)
        hintBeta h Hbeta hmin)

end

end BealRegular.TwentyThreeRealSubfieldDiscriminant
