import BealRegular.TwentyThreeRealSubfield

#print axioms BealRegular.TwentyThreeRealSubfield.cyclotomicFieldTwentyThree_isCMField
#print axioms BealRegular.TwentyThreeRealSubfield.maximalRealSubfield_finrank
#print axioms BealRegular.TwentyThreeRealSubfield.zeta23_isPrimitiveRoot
#print axioms BealRegular.TwentyThreeRealSubfield.alphaInCyclotomic_mem_maximalRealSubfield
#print axioms BealRegular.TwentyThreeRealSubfield.alpha_coe
#print axioms BealRegular.TwentyThreeRealSubfield.zeta23_pow_eleven_mul_aeval_realSubfieldPolynomial
#print axioms BealRegular.TwentyThreeRealSubfield.zeta23_geometric_sum_eq_zero
#print axioms BealRegular.TwentyThreeRealSubfield.aeval_realSubfieldPolynomial_alphaInCyclotomic
#print axioms BealRegular.TwentyThreeRealSubfield.aeval_realSubfieldPolynomial_alpha
