import BealRegular.TwentyThreeRealSubfieldRingOfIntegers

#print axioms BealRegular.TwentyThreeRealSubfieldRingOfIntegers.ringOfIntegersPowerBasis_gen
#print axioms BealRegular.TwentyThreeRealSubfieldRingOfIntegers.ringOfIntegersPowerBasis_dim
#print axioms BealRegular.TwentyThreeRealSubfieldRingOfIntegers.minpoly_int_betaInteger
#print axioms BealRegular.TwentyThreeRealSubfieldRingOfIntegers.betaInteger_adjoin_eq_top
#print axioms BealRegular.TwentyThreeRealSubfieldRingOfIntegers.betaInteger_exponent
#print axioms BealRegular.TwentyThreeRealSubfieldRingOfIntegers.isIntegralClosure_adjoin_alpha
#print axioms BealRegular.TwentyThreeRealSubfieldRingOfIntegers.alphaRingOfIntegersPowerBasis_gen
#print axioms BealRegular.TwentyThreeRealSubfieldRingOfIntegers.alphaRingOfIntegersPowerBasis_dim
#print axioms BealRegular.TwentyThreeRealSubfieldRingOfIntegers.minpoly_int_alphaInteger
#print axioms BealRegular.TwentyThreeRealSubfieldRingOfIntegers.aeval_realSubfieldPolynomial_alphaInteger
#print axioms BealRegular.TwentyThreeRealSubfieldRingOfIntegers.alphaInteger_adjoin_eq_top
#print axioms BealRegular.TwentyThreeRealSubfieldRingOfIntegers.alphaInteger_exponent
#print axioms BealRegular.TwentyThreeRealSubfieldRingOfIntegers.alphaPowerBasis_discr_eq_betaPowerBasis_discr
#print axioms BealRegular.TwentyThreeRealSubfieldRingOfIntegers.betaPowerBasis_discr
#print axioms BealRegular.TwentyThreeRealSubfieldRingOfIntegers.maximalRealSubfield_discr
#print axioms BealRegular.TwentyThreeRealSubfieldRingOfIntegers.sqrt_abs_maximalRealSubfield_discr
#print axioms BealRegular.TwentyThreeRealSubfieldRingOfIntegers.realMinkowskiBound_eq
#print axioms BealRegular.TwentyThreeRealSubfieldRingOfIntegers.realMinkowskiBound_floor
