import BealRegular.TwentyThreeRealSubfieldEisenstein

#print axioms BealRegular.TwentyThreeRealSubfieldEisenstein.shiftedRealSubfieldPolynomial_eq_comp
#print axioms BealRegular.TwentyThreeRealSubfieldEisenstein.shiftedRealSubfieldPolynomial_monic
#print axioms BealRegular.TwentyThreeRealSubfieldEisenstein.shiftedRealSubfieldPolynomial_natDegree
#print axioms BealRegular.TwentyThreeRealSubfieldEisenstein.shiftedRealSubfieldPolynomial_isEisensteinAt
#print axioms BealRegular.TwentyThreeRealSubfieldEisenstein.shiftedRealSubfieldPolynomial_irreducible
#print axioms BealRegular.TwentyThreeRealSubfieldEisenstein.realSubfieldPolynomial_monic
#print axioms BealRegular.TwentyThreeRealSubfieldEisenstein.realSubfieldPolynomial_natDegree
#print axioms BealRegular.TwentyThreeRealSubfieldEisenstein.translate_realSubfieldPolynomial
#print axioms BealRegular.TwentyThreeRealSubfieldEisenstein.realSubfieldPolynomial_irreducible
#print axioms BealRegular.TwentyThreeRealSubfieldEisenstein.realSubfieldPolynomialRat_monic
#print axioms BealRegular.TwentyThreeRealSubfieldEisenstein.realSubfieldPolynomialRat_irreducible
#print axioms BealRegular.TwentyThreeRealSubfieldEisenstein.aeval_realSubfieldPolynomialRat_alpha
#print axioms BealRegular.TwentyThreeRealSubfieldEisenstein.realSubfieldPolynomialRat_eq_minpoly_alpha
#print axioms BealRegular.TwentyThreeRealSubfieldEisenstein.minpoly_alpha_natDegree
#print axioms BealRegular.TwentyThreeRealSubfieldEisenstein.adjoin_alpha_eq_top
