module

public import BealRegular.TwentyThreeRealSubfieldDiscriminant
public import Mathlib.NumberTheory.NumberField.ClassNumber
public import Mathlib.NumberTheory.NumberField.Ideal.KummerDedekind

/-!
# The ring of integers and Minkowski bound of the real subfield at 23

The maximal-order theorem for the Eisenstein generator is transported to the
canonical ring of integers.  This gives an explicit integral power basis,
the absolute field discriminant `23^10`, and the exact Minkowski floor `900`.
-/

@[expose] public section

namespace BealRegular.TwentyThreeRealSubfieldRingOfIntegers

open BealRegular.TwentyThreeRealSubfield
open BealRegular.TwentyThreeRealSubfieldEisenstein
open BealRegular.TwentyThreeRealSubfieldPowerBasis
open BealRegular.TwentyThreeRealSubfieldDiscriminant
open Polynomial
open scoped nonZeroDivisors

noncomputable section

local notation "K23" => CyclotomicField 23 ℚ
local notation "K23plus" => NumberField.maximalRealSubfield K23

/-- The canonical equivalence from the order generated by `beta` to the ring
of integers of the real subfield. -/
noncomputable def adjoinBetaEquivRingOfIntegers :
    Algebra.adjoin ℤ ({beta} : Set K23plus) ≃ₐ[ℤ]
      NumberField.RingOfIntegers K23plus :=
  let _ := isIntegralClosure_adjoin_beta
  IsIntegralClosure.equiv ℤ (Algebra.adjoin ℤ ({beta} : Set K23plus))
    K23plus (NumberField.RingOfIntegers K23plus)

/-- The integral power basis generated by the Eisenstein translate `beta`. -/
noncomputable def ringOfIntegersPowerBasis :
    PowerBasis ℤ (NumberField.RingOfIntegers K23plus) :=
  (Algebra.adjoin.powerBasis' beta_isIntegral_int).map
    adjoinBetaEquivRingOfIntegers

/-- The Eisenstein generator as an element of the canonical ring of integers. -/
abbrev betaInteger : NumberField.RingOfIntegers K23plus :=
  ⟨beta, beta_isIntegral_int⟩

@[simp]
theorem coe_adjoinBetaEquivRingOfIntegers
    (x : Algebra.adjoin ℤ ({beta} : Set K23plus)) :
    ((adjoinBetaEquivRingOfIntegers x :
      NumberField.RingOfIntegers K23plus) : K23plus) = x := by
  letI : IsIntegralClosure (Algebra.adjoin ℤ ({beta} : Set K23plus)) ℤ
      K23plus := isIntegralClosure_adjoin_beta
  change algebraMap (NumberField.RingOfIntegers K23plus) K23plus
      (adjoinBetaEquivRingOfIntegers x) =
    algebraMap (Algebra.adjoin ℤ ({beta} : Set K23plus)) K23plus x
  unfold adjoinBetaEquivRingOfIntegers
  exact IsIntegralClosure.algebraMap_equiv ℤ
    (Algebra.adjoin ℤ ({beta} : Set K23plus)) K23plus
    (NumberField.RingOfIntegers K23plus) x

@[simp]
theorem ringOfIntegersPowerBasis_gen :
    ringOfIntegersPowerBasis.gen = betaInteger := by
  apply NumberField.RingOfIntegers.ext
  rw [ringOfIntegersPowerBasis, PowerBasis.map_gen,
    coe_adjoinBetaEquivRingOfIntegers,
    Algebra.adjoin.powerBasis'_gen]
  rfl

@[simp]
theorem ringOfIntegersPowerBasis_dim :
    ringOfIntegersPowerBasis.dim = 11 := by
  simp [ringOfIntegersPowerBasis,
    minpoly_int_beta_eq_shiftedRealSubfieldPolynomial,
    shiftedRealSubfieldPolynomial_natDegree]

theorem minpoly_int_betaInteger :
    minpoly ℤ betaInteger = shiftedRealSubfieldPolynomial := by
  rw [← minpoly.algHom_eq
    (IsScalarTower.toAlgHom ℤ (NumberField.RingOfIntegers K23plus) K23plus)
    NumberField.RingOfIntegers.coe_injective betaInteger]
  exact minpoly_int_beta_eq_shiftedRealSubfieldPolynomial

theorem betaInteger_adjoin_eq_top :
    Algebra.adjoin ℤ ({betaInteger} :
      Set (NumberField.RingOfIntegers K23plus)) = ⊤ := by
  rw [← ringOfIntegersPowerBasis_gen]
  exact ringOfIntegersPowerBasis.adjoin_gen_eq_top

/-- The Kummer--Dedekind conductor exponent of `betaInteger` is one, so every
rational prime is eligible for factorization through its minimal polynomial. -/
theorem betaInteger_exponent : RingOfIntegers.exponent betaInteger = 1 :=
  RingOfIntegers.exponent_eq_one_iff.mpr betaInteger_adjoin_eq_top

/-- The order generated by `alpha` is also an integral closure, because it is
the same subalgebra as the order generated by `beta`. -/
theorem isIntegralClosure_adjoin_alpha :
    IsIntegralClosure (Algebra.adjoin ℤ ({alpha} : Set K23plus)) ℤ
      K23plus := by
  refine ⟨Subtype.val_injective,
    @fun x => ⟨fun h => ?_, fun h => ?_⟩⟩
  · obtain ⟨y, hy⟩ := isIntegralClosure_adjoin_beta.isIntegral_iff.mp h
    refine ⟨⟨x, ?_⟩, rfl⟩
    rw [adjoin_int_alpha_eq_adjoin_beta, ← hy]
    exact y.property
  · obtain ⟨y, rfl⟩ := h
    exact IsIntegral.algebraMap
      ((le_integralClosure_iff_isIntegral.mp
        (adjoin_le_integralClosure alpha_isIntegral_int)).isIntegral y)

/-- The canonical equivalence from the order generated by `alpha` to the ring
of integers. -/
noncomputable def adjoinAlphaEquivRingOfIntegers :
    Algebra.adjoin ℤ ({alpha} : Set K23plus) ≃ₐ[ℤ]
      NumberField.RingOfIntegers K23plus :=
  let _ := isIntegralClosure_adjoin_alpha
  IsIntegralClosure.equiv ℤ (Algebra.adjoin ℤ ({alpha} : Set K23plus))
    K23plus (NumberField.RingOfIntegers K23plus)

/-- The integral power basis generated by `alpha`. -/
noncomputable def alphaRingOfIntegersPowerBasis :
    PowerBasis ℤ (NumberField.RingOfIntegers K23plus) :=
  (Algebra.adjoin.powerBasis' alpha_isIntegral_int).map
    adjoinAlphaEquivRingOfIntegers

/-- The original generator as an element of the canonical ring of integers. -/
abbrev alphaInteger : NumberField.RingOfIntegers K23plus :=
  ⟨alpha, alpha_isIntegral_int⟩

@[simp]
theorem coe_adjoinAlphaEquivRingOfIntegers
    (x : Algebra.adjoin ℤ ({alpha} : Set K23plus)) :
    ((adjoinAlphaEquivRingOfIntegers x :
      NumberField.RingOfIntegers K23plus) : K23plus) = x := by
  letI : IsIntegralClosure (Algebra.adjoin ℤ ({alpha} : Set K23plus)) ℤ
      K23plus := isIntegralClosure_adjoin_alpha
  change algebraMap (NumberField.RingOfIntegers K23plus) K23plus
      (adjoinAlphaEquivRingOfIntegers x) =
    algebraMap (Algebra.adjoin ℤ ({alpha} : Set K23plus)) K23plus x
  unfold adjoinAlphaEquivRingOfIntegers
  exact IsIntegralClosure.algebraMap_equiv ℤ
    (Algebra.adjoin ℤ ({alpha} : Set K23plus)) K23plus
    (NumberField.RingOfIntegers K23plus) x

@[simp]
theorem alphaRingOfIntegersPowerBasis_gen :
    alphaRingOfIntegersPowerBasis.gen = alphaInteger := by
  apply NumberField.RingOfIntegers.ext
  rw [alphaRingOfIntegersPowerBasis, PowerBasis.map_gen,
    coe_adjoinAlphaEquivRingOfIntegers,
    Algebra.adjoin.powerBasis'_gen]
  rfl

@[simp]
theorem alphaRingOfIntegersPowerBasis_dim :
    alphaRingOfIntegersPowerBasis.dim = 11 := by
  simp [alphaRingOfIntegersPowerBasis,
    ← realSubfieldPolynomial_eq_minpoly_int_alpha,
    realSubfieldPolynomial_natDegree]

theorem minpoly_int_alphaInteger :
    minpoly ℤ alphaInteger = realSubfieldPolynomial := by
  rw [← minpoly.algHom_eq
    (IsScalarTower.toAlgHom ℤ (NumberField.RingOfIntegers K23plus) K23plus)
    NumberField.RingOfIntegers.coe_injective alphaInteger]
  exact realSubfieldPolynomial_eq_minpoly_int_alpha.symm

theorem aeval_realSubfieldPolynomial_alphaInteger :
    aeval alphaInteger realSubfieldPolynomial = 0 := by
  rw [← minpoly_int_alphaInteger]
  exact minpoly.aeval ℤ alphaInteger

theorem alphaInteger_adjoin_eq_top :
    Algebra.adjoin ℤ ({alphaInteger} :
      Set (NumberField.RingOfIntegers K23plus)) = ⊤ := by
  rw [← alphaRingOfIntegersPowerBasis_gen]
  exact alphaRingOfIntegersPowerBasis.adjoin_gen_eq_top

theorem alphaInteger_exponent : RingOfIntegers.exponent alphaInteger = 1 :=
  RingOfIntegers.exponent_eq_one_iff.mpr alphaInteger_adjoin_eq_top

/-- Translating the generator by two preserves the rational basis
discriminant. -/
theorem alphaPowerBasis_discr_eq_betaPowerBasis_discr :
    Algebra.discr ℚ alphaPowerBasis.basis =
      Algebra.discr ℚ betaPowerBasis.basis := by
  have HalphaBeta :
      aeval alphaPowerBasis.gen (X + C (2 : ℤ)) = betaPowerBasis.gen := by
    rw [map_add, aeval_X, aeval_C, alphaPowerBasis_gen,
      betaPowerBasis_gen]
    simp [beta]
  have HbetaAlpha :
      aeval betaPowerBasis.gen (X - C (2 : ℤ)) = alphaPowerBasis.gen := by
    rw [map_sub, aeval_X, aeval_C, alphaPowerBasis_gen,
      betaPowerBasis_gen]
    simp [beta]
  have hminAlpha :=
    minpoly.isIntegrallyClosed_eq_field_fractions' ℚ alpha_isIntegral_int
  have hminBeta :=
    minpoly.isIntegrallyClosed_eq_field_fractions' ℚ beta_isIntegral_int
  have hAlphaBeta : ∀ i j, IsIntegral ℤ
      (alphaPowerBasis.basis.toMatrix betaPowerBasis.basis i j) :=
    PowerBasis.toMatrix_isIntegral (B := alphaPowerBasis)
      (B' := betaPowerBasis) HalphaBeta alpha_isIntegral_int hminAlpha
  have hBetaAlpha : ∀ i j, IsIntegral ℤ
      (betaPowerBasis.basis.toMatrix alphaPowerBasis.basis i j) :=
    PowerBasis.toMatrix_isIntegral (B := betaPowerBasis)
      (B' := alphaPowerBasis) HbetaAlpha beta_isIntegral_int hminBeta
  exact Algebra.discr_eq_discr_of_toMatrix_coeff_isIntegral K23plus
    hAlphaBeta hBetaAlpha

theorem betaPowerBasis_discr :
    Algebra.discr ℚ betaPowerBasis.basis = (23 : ℚ) ^ 10 := by
  rw [← alphaPowerBasis_discr_eq_betaPowerBasis_discr]
  exact alphaPowerBasis_discr

/-- The canonical absolute discriminant of the real subfield is `23^10`. -/
theorem maximalRealSubfield_discr :
    NumberField.discr K23plus = (23 : ℤ) ^ 10 := by
  apply (algebraMap ℤ ℚ).injective_int
  rw [← NumberField.discr_eq_discr _ ringOfIntegersPowerBasis.basis,
    ← Algebra.discr_localizationLocalization ℤ ℤ⁰ K23plus]
  convert betaPowerBasis_discr using 1
  · have hdim : ringOfIntegersPowerBasis.dim = betaPowerBasis.dim := by
      rw [ringOfIntegersPowerBasis_dim, betaPowerBasis_dim]
    rw [← Algebra.discr_reindex _ _ (finCongr hdim)]
    congr 1
    ext i
    simp_rw [Function.comp_apply,
      Module.Basis.localizationLocalization_apply,
      PowerBasis.coe_basis, ringOfIntegersPowerBasis_gen]
    convert ← (betaPowerBasis.basis_eq_pow i).symm using 1
    simp [betaInteger]
  · norm_num

/-- The real-valued Minkowski expression used by Mathlib's class-number
reduction theorem. -/
def realMinkowskiBound : ℝ :=
  (4 / Real.pi) ^ NumberField.InfinitePlace.nrComplexPlaces K23plus *
    ((Nat.factorial (Module.finrank ℚ K23plus) : ℝ) /
      (Module.finrank ℚ K23plus : ℝ) ^ (Module.finrank ℚ K23plus) *
        √|NumberField.discr K23plus|)

theorem sqrt_abs_maximalRealSubfield_discr :
    √|(NumberField.discr K23plus : ℝ)| = (23 : ℝ) ^ 5 := by
  rw [maximalRealSubfield_discr]
  norm_num [abs_of_nonneg]
  rw [show (41426511213649 : ℝ) = (6436343 : ℝ) ^ 2 by norm_num,
    Real.sqrt_sq (by positivity)]

theorem realMinkowskiBound_eq :
    realMinkowskiBound =
      (Nat.factorial 11 : ℝ) / (11 : ℝ) ^ 11 * (23 : ℝ) ^ 5 := by
  rw [realMinkowskiBound,
    NumberField.IsTotallyReal.nrComplexPlaces_eq_zero,
    maximalRealSubfield_finrank, sqrt_abs_maximalRealSubfield_discr]
  norm_num

/-- The exact natural-number floor of the real-subfield Minkowski bound. -/
theorem realMinkowskiBound_floor : ⌊realMinkowskiBound⌋₊ = 900 := by
  rw [realMinkowskiBound_eq]
  rw [Nat.floor_eq_iff (by positivity)]
  norm_num [Nat.factorial]

end

end BealRegular.TwentyThreeRealSubfieldRingOfIntegers
