import BealRegular.TwentyThreeRealSubfieldDiscriminant

#print axioms BealRegular.TwentyThreeRealSubfieldDiscriminant.realSubfieldPolynomialRat_discr
#print axioms BealRegular.TwentyThreeRealSubfieldDiscriminant.realSubfieldPolynomial_discr
#print axioms BealRegular.TwentyThreeRealSubfieldDiscriminant.alphaPowerBasis_discr
#print axioms BealRegular.TwentyThreeRealSubfieldDiscriminant.adjoin_int_alpha_eq_adjoin_beta
#print axioms BealRegular.TwentyThreeRealSubfieldDiscriminant.isIntegralClosure_adjoin_beta
