module

public import BealRegular.TwentyThreeRealCertificateBase

/-!
This file is generated by `render_23_real_certificates.mjs` from
`certificates_23_real.json`.  Corpus SHA-256:
`21e554a6a6a2b0d78efef741813a98d5269feebdbf11f9219bb6f8c03d6cc9e7`.
Do not edit this file by hand.
-/

@[expose] public section

open Ideal NumberField Polynomial RingOfIntegers

namespace BealRegular.TwentyThreeRealCertificates.Q229

open BealRegular.PrincipalIdealCertificate
open BealRegular.TwentyThreeRealCertificateBase

noncomputable section

local instance : Fact (Nat.Prime 229) := ⟨by norm_num⟩

def P : ℤ[X] := X - C 6

def Q : ℤ[X] := X ^ 10 + C 5 * X ^ 9 + C 20 * X ^ 8 + C 129 * X ^ 7 + C 810 * X ^ 6 + C 4832 * X ^ 5
  + C 28936 * X ^ 4 + C 173651 * X ^ 3 + C 1041941 * X ^ 2 + C 6251631 * X + C 37509780

def A : ℤ[X] := C 982789

def G : ℤ[X] := -X ^ 10 + C 9 * X ^ 8 - C 28 * X ^ 6 + X ^ 5 + C 35 * X ^ 4 - C 4 * X ^ 3
  - C 15 * X ^ 2 + C 3 * X + C 2

def Qq : ℤ[X] := -C 79 * X ^ 10 + C 63 * X ^ 9 + C 710 * X ^ 8 - C 573 * X ^ 7 - C 2160 * X ^ 6
  + C 1847 * X ^ 5 + C 2453 * X ^ 4 - C 2474 * X ^ 3 - C 663 * X ^ 2 + C 1100 * X - C 25

def Rq : ℤ[X] := -C 79 * X ^ 9 - C 16 * X ^ 8 + C 615 * X ^ 7 + C 26 * X ^ 6 - C 1598 * X ^ 5
  + C 338 * X ^ 4 + C 1587 * X ^ 3 - C 870 * X ^ 2 - C 451 * X + C 279

def QP : ℤ[X] := C 2 * X ^ 10 - C 2 * X ^ 9 - C 18 * X ^ 8 + C 18 * X ^ 7 + C 55 * X ^ 6
  - C 57 * X ^ 5 - C 63 * X ^ 4 + C 74 * X ^ 3 + C 17 * X ^ 2 - C 31 * X + C 1

def RP : ℤ[X] := C 2 * X ^ 9 - C 16 * X ^ 7 + C 2 * X ^ 6 + C 43 * X ^ 5 - C 14 * X ^ 4
  - C 44 * X ^ 3 + C 26 * X ^ 2 + C 12 * X - C 8

def C1 : ℤ[X] := -X ^ 9 - C 6 * X ^ 8 - C 27 * X ^ 7 - C 162 * X ^ 6 - C 1000 * X ^ 5
  - C 5999 * X ^ 4 - C 35959 * X ^ 3 - C 215758 * X ^ 2 - C 1294563 * X - C 7767375

def C2 : ℤ[X] := -C 203512

set_option maxHeartbeats 0 in
-- Exact normalization of the displayed polynomial identity can be expensive.
set_option maxRecDepth 12000 in
/-- The factor identity in ℤ[X]. -/
theorem factorization_identity :
    P * Q + C (229 : ℤ) * A = Phi := by
  simp only [P, Q, A, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  ring

set_option maxHeartbeats 0 in
-- Exact normalization of the three displayed Bezout identities can be expensive.
set_option maxRecDepth 12000 in
/-- The three exact Bezout identities certifying the Kummer--Dedekind ideal. -/
theorem principal_identities :
    C (229 : ℤ) = G * Qq + Phi * Rq ∧
      P = G * QP + Phi * RP ∧
        G = C2 * C (229 : ℤ) + C1 * P + Phi * 0 := by
  simp only [P, G, Qq, Rq, QP, RP, C1, C2, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  constructor
  · ring
  constructor <;> ring

theorem P_monic : P.Monic := by
  simp only [P]
  monicity!

theorem map_P_irreducible :
    Irreducible (P.map (Int.castRingHom (ZMod 229))) := by
  apply Polynomial.irreducible_of_degree_eq_one
  simp only [P, Polynomial.map_sub, map_X, map_C]
  compute_degree!

theorem map_P_dvd_Phi :
    P.map (Int.castRingHom (ZMod 229)) ∣
      Phi.map (Int.castRingHom (ZMod 229)) := by
  refine ⟨Q.map (Int.castRingHom (ZMod 229)), ?_⟩
  have h := congrArg (Polynomial.map (Int.castRingHom (ZMod 229)))
    factorization_identity
  simp only [Polynomial.map_add, Polynomial.map_mul, map_C] at h
  have hq : Int.castRingHom (ZMod 229) (229 : ℤ) = 0 := by decide
  rw [hq, C_0, zero_mul, add_zero] at h
  exact h.symm

theorem map_P_mem_monicFactorsMod :
    P.map (Int.castRingHom (ZMod 229)) ∈ monicFactorsMod theta 229 := by
  rw [Multiset.mem_toFinset, Polynomial.mem_normalizedFactors_iff
    (map_monic_ne_zero (minpoly.monic theta.isIntegral))]
  refine ⟨map_P_irreducible, P_monic.map _, ?_⟩
  rw [← Phi_eq_minpoly]
  exact map_P_dvd_Phi

theorem q_not_dvd_exponent : ¬ 229 ∣ exponent theta := by
  rw [theta_exponent]
  norm_num

/-- The prime above 229 selected by the displayed linear factor. -/
noncomputable def selectedPrime :
    primesOver (span {(229 : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  (NumberField.Ideal.primesOverSpanEquivMonicFactorsMod q_not_dvd_exponent).symm
    ⟨P.map (Int.castRingHom (ZMod 229)), map_P_mem_monicFactorsMod⟩

theorem selectedPrime_mem_primesOver :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) ∈
      primesOver (span {(229 : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  selectedPrime.property

theorem selectedPrime_eq_span :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) =
      span {algebraMap ℤ (NumberField.RingOfIntegers RealField) 229, aeval theta P} := by
  exact NumberField.Ideal.primesOverSpanEquivMonicFactorsMod_symm_apply_eq_span
    q_not_dvd_exponent map_P_mem_monicFactorsMod

/-- The selected prime above 229 is principal, with generator G(theta). -/
theorem selectedPrime_isPrincipal :
    Submodule.IsPrincipal
      (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) := by
  rcases principal_identities with ⟨hq, hP, hG⟩
  exact kummerDedekindPrime_isPrincipal_of_polynomial_certificate
    (F := P) (G := G) (Phi := Phi) (QA := Qq) (QB := QP)
    (RA := Rq) (RB := RP) (RG := 0) (CA := C2) (CB := C1)
    (p := 229) theta q_not_dvd_exponent map_P_mem_monicFactorsMod
    aeval_Phi_theta hq hP hG

/-- The exact branch shape consumed by the real-subfield Minkowski criterion. -/
theorem minkowski_branch :
    ∃ J ∈ primesOver (span {(229 : ℤ)})
        (NumberField.RingOfIntegers RealField),
      900 < 229 ^ J.inertiaDeg ℤ ∨ Submodule.IsPrincipal J :=
  ⟨selectedPrime, selectedPrime.property, Or.inr selectedPrime_isPrincipal⟩

end

end BealRegular.TwentyThreeRealCertificates.Q229
