import BealRegular.TwentyThreeRealSubfieldClassNumber

#print axioms BealRegular.TwentyThreeRealSubfieldClassNumber.maximalRealSubfield_isGalois
#print axioms BealRegular.TwentyThreeRealSubfieldClassNumber.norm_betaInteger
#print axioms BealRegular.TwentyThreeRealSubfieldClassNumber.absNorm_betaPrimeIdeal
#print axioms BealRegular.TwentyThreeRealSubfieldClassNumber.betaPrimeIdeal_isPrime
#print axioms BealRegular.TwentyThreeRealSubfieldClassNumber.betaPrimeIdeal_liesOver
#print axioms BealRegular.TwentyThreeRealSubfieldClassNumber.betaPrimeIdeal_mem_primesOver
#print axioms BealRegular.TwentyThreeRealSubfieldClassNumber.betaPrimeIdeal_isPrincipal
#print axioms BealRegular.TwentyThreeRealSubfieldClassNumber.isPrincipalIdealRing_of_one_prime_above
#print axioms BealRegular.TwentyThreeRealSubfieldClassNumber.classNumber_eq_one_of_one_prime_above
#print axioms BealRegular.TwentyThreeRealSubfieldClassNumber.prime_twentyThree_branch
#print axioms BealRegular.TwentyThreeRealSubfieldClassNumber.isPrincipalIdealRing_of_other_primes
#print axioms BealRegular.TwentyThreeRealSubfieldClassNumber.classNumber_eq_one_of_other_primes
