module

public import BealRegular.TwentyThreeRealCertificateBase

/-!
This file is generated by `render_23_real_certificates.mjs` from
`certificates_23_real.json`.  Corpus SHA-256:
`21e554a6a6a2b0d78efef741813a98d5269feebdbf11f9219bb6f8c03d6cc9e7`.
Do not edit this file by hand.
-/

@[expose] public section

open Ideal NumberField Polynomial RingOfIntegers

namespace BealRegular.TwentyThreeRealCertificates.Q277

open BealRegular.PrincipalIdealCertificate
open BealRegular.TwentyThreeRealCertificateBase

noncomputable section

local instance : Fact (Nat.Prime 277) := ⟨by norm_num⟩

def P : ℤ[X] := X - C 14

def Q : ℤ[X] := X ^ 10 + C 13 * X ^ 9 + C 172 * X ^ 8 + C 2417 * X ^ 7 + C 33874 * X ^ 6
  + C 474208 * X ^ 5 + C 6638856 * X ^ 4 + C 92944019 * X ^ 3 + C 1301216301 * X ^ 2
  + C 18217028199 * X + C 255038394780

def A : ℤ[X] := C 12890027173

def G : ℤ[X] := X ^ 10 - X ^ 9 - C 9 * X ^ 8 + C 8 * X ^ 7 + C 27 * X ^ 6 - C 21 * X ^ 5
  - C 29 * X ^ 4 + C 20 * X ^ 3 + C 6 * X ^ 2 - C 5 * X + C 2

def Qq : ℤ[X] := C 18 * X ^ 10 - C 43 * X ^ 9 - C 228 * X ^ 8 + C 294 * X ^ 7 + C 886 * X ^ 6
  - C 565 * X ^ 5 - C 1162 * X ^ 4 + C 151 * X ^ 3 + C 251 * X ^ 2 + C 197 * X + C 157

def Rq : ℤ[X] := -C 18 * X ^ 9 + C 43 * X ^ 8 + C 210 * X ^ 7 - C 251 * X ^ 6 - C 676 * X ^ 5
  + C 332 * X ^ 4 + C 461 * X ^ 3 + C 169 * X - C 37

def QP : ℤ[X] := -X ^ 10 + C 2 * X ^ 9 + C 12 * X ^ 8 - C 14 * X ^ 7 - C 45 * X ^ 6 + C 28 * X ^ 5
  + C 57 * X ^ 4 - C 9 * X ^ 3 - C 11 * X ^ 2 - C 9 * X - C 8

def RP : ℤ[X] := X ^ 9 - C 2 * X ^ 8 - C 11 * X ^ 7 + C 12 * X ^ 6 + C 34 * X ^ 5 - C 17 * X ^ 4
  - C 22 * X ^ 3 + X ^ 2 - C 9 * X + C 2

def C1 : ℤ[X] := X ^ 9 + C 13 * X ^ 8 + C 173 * X ^ 7 + C 2430 * X ^ 6 + C 34047 * X ^ 5
  + C 476637 * X ^ 4 + C 6672889 * X ^ 3 + C 93420466 * X ^ 2 + C 1307886530 * X + C 18310411415

def C2 : ℤ[X] := C 925435956

set_option maxHeartbeats 0 in
-- Exact normalization of the displayed polynomial identity can be expensive.
set_option maxRecDepth 12000 in
/-- The factor identity in ℤ[X]. -/
theorem factorization_identity :
    P * Q + C (277 : ℤ) * A = Phi := by
  simp only [P, Q, A, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  ring

set_option maxHeartbeats 0 in
-- Exact normalization of the three displayed Bezout identities can be expensive.
set_option maxRecDepth 12000 in
/-- The three exact Bezout identities certifying the Kummer--Dedekind ideal. -/
theorem principal_identities :
    C (277 : ℤ) = G * Qq + Phi * Rq ∧
      P = G * QP + Phi * RP ∧
        G = C2 * C (277 : ℤ) + C1 * P + Phi * 0 := by
  simp only [P, G, Qq, Rq, QP, RP, C1, C2, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  constructor
  · ring
  constructor <;> ring

theorem P_monic : P.Monic := by
  simp only [P]
  monicity!

theorem map_P_irreducible :
    Irreducible (P.map (Int.castRingHom (ZMod 277))) := by
  apply Polynomial.irreducible_of_degree_eq_one
  simp only [P, Polynomial.map_sub, map_X, map_C]
  compute_degree!

theorem map_P_dvd_Phi :
    P.map (Int.castRingHom (ZMod 277)) ∣
      Phi.map (Int.castRingHom (ZMod 277)) := by
  refine ⟨Q.map (Int.castRingHom (ZMod 277)), ?_⟩
  have h := congrArg (Polynomial.map (Int.castRingHom (ZMod 277)))
    factorization_identity
  simp only [Polynomial.map_add, Polynomial.map_mul, map_C] at h
  have hq : Int.castRingHom (ZMod 277) (277 : ℤ) = 0 := by decide
  rw [hq, C_0, zero_mul, add_zero] at h
  exact h.symm

theorem map_P_mem_monicFactorsMod :
    P.map (Int.castRingHom (ZMod 277)) ∈ monicFactorsMod theta 277 := by
  rw [Multiset.mem_toFinset, Polynomial.mem_normalizedFactors_iff
    (map_monic_ne_zero (minpoly.monic theta.isIntegral))]
  refine ⟨map_P_irreducible, P_monic.map _, ?_⟩
  rw [← Phi_eq_minpoly]
  exact map_P_dvd_Phi

theorem q_not_dvd_exponent : ¬ 277 ∣ exponent theta := by
  rw [theta_exponent]
  norm_num

/-- The prime above 277 selected by the displayed linear factor. -/
noncomputable def selectedPrime :
    primesOver (span {(277 : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  (NumberField.Ideal.primesOverSpanEquivMonicFactorsMod q_not_dvd_exponent).symm
    ⟨P.map (Int.castRingHom (ZMod 277)), map_P_mem_monicFactorsMod⟩

theorem selectedPrime_mem_primesOver :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) ∈
      primesOver (span {(277 : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  selectedPrime.property

theorem selectedPrime_eq_span :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) =
      span {algebraMap ℤ (NumberField.RingOfIntegers RealField) 277, aeval theta P} := by
  exact NumberField.Ideal.primesOverSpanEquivMonicFactorsMod_symm_apply_eq_span
    q_not_dvd_exponent map_P_mem_monicFactorsMod

/-- The selected prime above 277 is principal, with generator G(theta). -/
theorem selectedPrime_isPrincipal :
    Submodule.IsPrincipal
      (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) := by
  rcases principal_identities with ⟨hq, hP, hG⟩
  exact kummerDedekindPrime_isPrincipal_of_polynomial_certificate
    (F := P) (G := G) (Phi := Phi) (QA := Qq) (QB := QP)
    (RA := Rq) (RB := RP) (RG := 0) (CA := C2) (CB := C1)
    (p := 277) theta q_not_dvd_exponent map_P_mem_monicFactorsMod
    aeval_Phi_theta hq hP hG

/-- The exact branch shape consumed by the real-subfield Minkowski criterion. -/
theorem minkowski_branch :
    ∃ J ∈ primesOver (span {(277 : ℤ)})
        (NumberField.RingOfIntegers RealField),
      900 < 277 ^ J.inertiaDeg ℤ ∨ Submodule.IsPrincipal J :=
  ⟨selectedPrime, selectedPrime.property, Or.inr selectedPrime_isPrincipal⟩

end

end BealRegular.TwentyThreeRealCertificates.Q277
