module

public import BealRegular.PrincipalIdealCertificate
public import BealRegular.TwentyThreeRealSubfieldRingOfIntegers

/-!
This file is generated by `render_23_real_certificates.mjs` from
`certificates_23_real.json`.  Corpus SHA-256:
`21e554a6a6a2b0d78efef741813a98d5269feebdbf11f9219bb6f8c03d6cc9e7`.
Do not edit this file by hand.
-/

@[expose] public section

open NumberField Polynomial RingOfIntegers

namespace BealRegular.TwentyThreeRealCertificateBase

open BealRegular.TwentyThreeRealSubfield
open BealRegular.TwentyThreeRealSubfieldRingOfIntegers

noncomputable section

/-- The degree-eleven maximal real subfield of the 23rd cyclotomic field. -/
abbrev RealField := NumberField.maximalRealSubfield (CyclotomicField 23 ℚ)

/-- The integral real-subfield generator alpha. -/
abbrev theta : NumberField.RingOfIntegers RealField := alphaInteger

/-- The minimal polynomial of theta. -/
abbrev Phi : ℤ[X] := realSubfieldPolynomial

theorem Phi_eq_minpoly : Phi = minpoly ℤ theta := by
  exact minpoly_int_alphaInteger.symm

theorem aeval_Phi_theta : aeval theta Phi = 0 := by
  exact aeval_realSubfieldPolynomial_alphaInteger

theorem theta_exponent : exponent theta = 1 := alphaInteger_exponent

end


end BealRegular.TwentyThreeRealCertificateBase
