module

public import BealRegular.TwentyThreeRealCertificateBase

/-!
This file is generated by `render_23_real_certificates.mjs` from
`certificates_23_real.json`.  Corpus SHA-256:
`21e554a6a6a2b0d78efef741813a98d5269feebdbf11f9219bb6f8c03d6cc9e7`.
Do not edit this file by hand.
-/

@[expose] public section

open Ideal NumberField Polynomial RingOfIntegers

namespace BealRegular.TwentyThreeRealCertificates.Q367

open BealRegular.PrincipalIdealCertificate
open BealRegular.TwentyThreeRealCertificateBase

noncomputable section

local instance : Fact (Nat.Prime 367) := ⟨by norm_num⟩

def P : ℤ[X] := X - C 5

def Q : ℤ[X] := X ^ 10 + C 4 * X ^ 9 + C 10 * X ^ 8 + C 59 * X ^ 7 + C 331 * X ^ 6 + C 1627 * X ^ 5
  + C 8079 * X ^ 4 + C 40430 * X ^ 3 + C 202185 * X ^ 2 + C 1010910 * X + C 5054544

def A : ℤ[X] := C 68863

def G : ℤ[X] := X ^ 9 - C 9 * X ^ 7 + C 28 * X ^ 5 - C 34 * X ^ 3 + C 12 * X + C 1

def Qq : ℤ[X] := C 15 * X ^ 10 + C 60 * X ^ 9 - C 217 * X ^ 8 - C 583 * X ^ 7 + C 928 * X ^ 6
  + C 2018 * X ^ 5 - C 1393 * X ^ 4 - C 2770 * X ^ 3 + C 621 * X ^ 2 + C 1045 * X - C 3

def Rq : ℤ[X] := -C 15 * X ^ 8 - C 75 * X ^ 7 + C 127 * X ^ 6 + C 635 * X ^ 5 - C 181 * X ^ 4
  - C 1639 * X ^ 3 - C 345 * X ^ 2 + C 1211 * X + C 370

def QP : ℤ[X] := -X ^ 9 + X ^ 8 + C 9 * X ^ 7 - C 6 * X ^ 6 - C 29 * X ^ 5 + C 10 * X ^ 4
  + C 38 * X ^ 3 - C 5 * X ^ 2 - C 14 * X

def RP : ℤ[X] := X ^ 7 - C 8 * X ^ 5 - C 2 * X ^ 4 + C 20 * X ^ 3 + C 8 * X ^ 2 - C 15 * X - C 5

def C1 : ℤ[X] := X ^ 8 + C 5 * X ^ 7 + C 16 * X ^ 6 + C 80 * X ^ 5 + C 428 * X ^ 4 + C 2140 * X ^ 3
  + C 10666 * X ^ 2 + C 53330 * X + C 266662

def C2 : ℤ[X] := C 3633

set_option maxHeartbeats 0 in
-- Exact normalization of the displayed polynomial identity can be expensive.
set_option maxRecDepth 12000 in
/-- The factor identity in ℤ[X]. -/
theorem factorization_identity :
    P * Q + C (367 : ℤ) * A = Phi := by
  simp only [P, Q, A, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  ring

set_option maxHeartbeats 0 in
-- Exact normalization of the three displayed Bezout identities can be expensive.
set_option maxRecDepth 12000 in
/-- The three exact Bezout identities certifying the Kummer--Dedekind ideal. -/
theorem principal_identities :
    C (367 : ℤ) = G * Qq + Phi * Rq ∧
      P = G * QP + Phi * RP ∧
        G = C2 * C (367 : ℤ) + C1 * P + Phi * 0 := by
  simp only [P, G, Qq, Rq, QP, RP, C1, C2, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  constructor
  · ring
  constructor <;> ring

theorem P_monic : P.Monic := by
  simp only [P]
  monicity!

theorem map_P_irreducible :
    Irreducible (P.map (Int.castRingHom (ZMod 367))) := by
  apply Polynomial.irreducible_of_degree_eq_one
  simp only [P, Polynomial.map_sub, map_X, map_C]
  compute_degree!

theorem map_P_dvd_Phi :
    P.map (Int.castRingHom (ZMod 367)) ∣
      Phi.map (Int.castRingHom (ZMod 367)) := by
  refine ⟨Q.map (Int.castRingHom (ZMod 367)), ?_⟩
  have h := congrArg (Polynomial.map (Int.castRingHom (ZMod 367)))
    factorization_identity
  simp only [Polynomial.map_add, Polynomial.map_mul, map_C] at h
  have hq : Int.castRingHom (ZMod 367) (367 : ℤ) = 0 := by decide
  rw [hq, C_0, zero_mul, add_zero] at h
  exact h.symm

theorem map_P_mem_monicFactorsMod :
    P.map (Int.castRingHom (ZMod 367)) ∈ monicFactorsMod theta 367 := by
  rw [Multiset.mem_toFinset, Polynomial.mem_normalizedFactors_iff
    (map_monic_ne_zero (minpoly.monic theta.isIntegral))]
  refine ⟨map_P_irreducible, P_monic.map _, ?_⟩
  rw [← Phi_eq_minpoly]
  exact map_P_dvd_Phi

theorem q_not_dvd_exponent : ¬ 367 ∣ exponent theta := by
  rw [theta_exponent]
  norm_num

/-- The prime above 367 selected by the displayed linear factor. -/
noncomputable def selectedPrime :
    primesOver (span {(367 : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  (NumberField.Ideal.primesOverSpanEquivMonicFactorsMod q_not_dvd_exponent).symm
    ⟨P.map (Int.castRingHom (ZMod 367)), map_P_mem_monicFactorsMod⟩

theorem selectedPrime_mem_primesOver :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) ∈
      primesOver (span {(367 : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  selectedPrime.property

theorem selectedPrime_eq_span :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) =
      span {algebraMap ℤ (NumberField.RingOfIntegers RealField) 367, aeval theta P} := by
  exact NumberField.Ideal.primesOverSpanEquivMonicFactorsMod_symm_apply_eq_span
    q_not_dvd_exponent map_P_mem_monicFactorsMod

/-- The selected prime above 367 is principal, with generator G(theta). -/
theorem selectedPrime_isPrincipal :
    Submodule.IsPrincipal
      (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) := by
  rcases principal_identities with ⟨hq, hP, hG⟩
  exact kummerDedekindPrime_isPrincipal_of_polynomial_certificate
    (F := P) (G := G) (Phi := Phi) (QA := Qq) (QB := QP)
    (RA := Rq) (RB := RP) (RG := 0) (CA := C2) (CB := C1)
    (p := 367) theta q_not_dvd_exponent map_P_mem_monicFactorsMod
    aeval_Phi_theta hq hP hG

/-- The exact branch shape consumed by the real-subfield Minkowski criterion. -/
theorem minkowski_branch :
    ∃ J ∈ primesOver (span {(367 : ℤ)})
        (NumberField.RingOfIntegers RealField),
      900 < 367 ^ J.inertiaDeg ℤ ∨ Submodule.IsPrincipal J :=
  ⟨selectedPrime, selectedPrime.property, Or.inr selectedPrime_isPrincipal⟩

end

end BealRegular.TwentyThreeRealCertificates.Q367
