module

public import BealRegular.TwentyThreeRealCertificateBase

/-!
This file is generated by `render_23_real_certificates.mjs` from
`certificates_23_real.json`.  Corpus SHA-256:
`21e554a6a6a2b0d78efef741813a98d5269feebdbf11f9219bb6f8c03d6cc9e7`.
Do not edit this file by hand.
-/

@[expose] public section

open Ideal NumberField Polynomial RingOfIntegers

namespace BealRegular.TwentyThreeRealCertificates.Q643

open BealRegular.PrincipalIdealCertificate
open BealRegular.TwentyThreeRealCertificateBase

noncomputable section

local instance : Fact (Nat.Prime 643) := ⟨by norm_num⟩

def P : ℤ[X] := X + C 21

def Q : ℤ[X] := X ^ 10 - C 22 * X ^ 9 + C 452 * X ^ 8 - C 9483 * X ^ 7 + C 199179 * X ^ 6
  - C 4182787 * X ^ 5 + C 87838471 * X ^ 4 - C 1844607856 * X ^ 3 + C 38736765011 * X ^ 2
  - C 813472065246 * X + C 17082913370160

def A : ℤ[X] := -C 557917855013

def G : ℤ[X] := X ^ 10 - C 2 * X ^ 9 - C 10 * X ^ 8 + C 17 * X ^ 7 + C 37 * X ^ 6 - C 48 * X ^ 5
  - C 62 * X ^ 4 + C 50 * X ^ 3 + C 45 * X ^ 2 - C 14 * X - C 10

def Qq : ℤ[X] := C 7 * X ^ 10 - C 154 * X ^ 9 - C 51 * X ^ 8 + C 1134 * X ^ 7 + C 229 * X ^ 6
  - C 2433 * X ^ 5 - C 739 * X ^ 4 + C 975 * X ^ 3 + C 989 * X ^ 2 + C 988 * X - C 214

def Rq : ℤ[X] := -C 7 * X ^ 9 + C 161 * X ^ 8 - C 96 * X ^ 7 - C 1318 * X ^ 6 + C 413 * X ^ 5
  + C 3237 * X ^ 4 + C 615 * X ^ 3 - C 1691 * X ^ 2 - C 2098 * X - C 1497

def QP : ℤ[X] := -C 5 * X ^ 9 + C 37 * X ^ 7 + C 4 * X ^ 6 - C 80 * X ^ 5 - C 23 * X ^ 4
  + C 33 * X ^ 3 + C 34 * X ^ 2 + C 32 * X - C 7

def RP : ℤ[X] := C 5 * X ^ 8 - C 5 * X ^ 7 - C 42 * X ^ 6 + C 18 * X ^ 5 + C 106 * X ^ 4
  + C 18 * X ^ 3 - C 58 * X ^ 2 - C 71 * X - C 49

def C1 : ℤ[X] := X ^ 9 - C 23 * X ^ 8 + C 473 * X ^ 7 - C 9916 * X ^ 6 + C 208273 * X ^ 5
  - C 4373781 * X ^ 4 + C 91849339 * X ^ 3 - C 1928836069 * X ^ 2 + C 40505557494 * X
  - C 850616707388

def C2 : ℤ[X] := C 27780638966

set_option maxHeartbeats 0 in
-- Exact normalization of the displayed polynomial identity can be expensive.
set_option maxRecDepth 12000 in
/-- The factor identity in ℤ[X]. -/
theorem factorization_identity :
    P * Q + C (643 : ℤ) * A = Phi := by
  simp only [P, Q, A, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  ring

set_option maxHeartbeats 0 in
-- Exact normalization of the three displayed Bezout identities can be expensive.
set_option maxRecDepth 12000 in
/-- The three exact Bezout identities certifying the Kummer--Dedekind ideal. -/
theorem principal_identities :
    C (643 : ℤ) = G * Qq + Phi * Rq ∧
      P = G * QP + Phi * RP ∧
        G = C2 * C (643 : ℤ) + C1 * P + Phi * 0 := by
  simp only [P, G, Qq, Rq, QP, RP, C1, C2, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  constructor
  · ring
  constructor <;> ring

theorem P_monic : P.Monic := by
  simp only [P]
  monicity!

theorem map_P_irreducible :
    Irreducible (P.map (Int.castRingHom (ZMod 643))) := by
  apply Polynomial.irreducible_of_degree_eq_one
  simp only [P, Polynomial.map_add, map_X, map_C]
  compute_degree!

theorem map_P_dvd_Phi :
    P.map (Int.castRingHom (ZMod 643)) ∣
      Phi.map (Int.castRingHom (ZMod 643)) := by
  refine ⟨Q.map (Int.castRingHom (ZMod 643)), ?_⟩
  have h := congrArg (Polynomial.map (Int.castRingHom (ZMod 643)))
    factorization_identity
  simp only [Polynomial.map_add, Polynomial.map_mul, map_C] at h
  have hq : Int.castRingHom (ZMod 643) (643 : ℤ) = 0 := by decide
  rw [hq, C_0, zero_mul, add_zero] at h
  exact h.symm

theorem map_P_mem_monicFactorsMod :
    P.map (Int.castRingHom (ZMod 643)) ∈ monicFactorsMod theta 643 := by
  rw [Multiset.mem_toFinset, Polynomial.mem_normalizedFactors_iff
    (map_monic_ne_zero (minpoly.monic theta.isIntegral))]
  refine ⟨map_P_irreducible, P_monic.map _, ?_⟩
  rw [← Phi_eq_minpoly]
  exact map_P_dvd_Phi

theorem q_not_dvd_exponent : ¬ 643 ∣ exponent theta := by
  rw [theta_exponent]
  norm_num

/-- The prime above 643 selected by the displayed linear factor. -/
noncomputable def selectedPrime :
    primesOver (span {(643 : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  (NumberField.Ideal.primesOverSpanEquivMonicFactorsMod q_not_dvd_exponent).symm
    ⟨P.map (Int.castRingHom (ZMod 643)), map_P_mem_monicFactorsMod⟩

theorem selectedPrime_mem_primesOver :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) ∈
      primesOver (span {(643 : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  selectedPrime.property

theorem selectedPrime_eq_span :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) =
      span {algebraMap ℤ (NumberField.RingOfIntegers RealField) 643, aeval theta P} := by
  exact NumberField.Ideal.primesOverSpanEquivMonicFactorsMod_symm_apply_eq_span
    q_not_dvd_exponent map_P_mem_monicFactorsMod

/-- The selected prime above 643 is principal, with generator G(theta). -/
theorem selectedPrime_isPrincipal :
    Submodule.IsPrincipal
      (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) := by
  rcases principal_identities with ⟨hq, hP, hG⟩
  exact kummerDedekindPrime_isPrincipal_of_polynomial_certificate
    (F := P) (G := G) (Phi := Phi) (QA := Qq) (QB := QP)
    (RA := Rq) (RB := RP) (RG := 0) (CA := C2) (CB := C1)
    (p := 643) theta q_not_dvd_exponent map_P_mem_monicFactorsMod
    aeval_Phi_theta hq hP hG

/-- The exact branch shape consumed by the real-subfield Minkowski criterion. -/
theorem minkowski_branch :
    ∃ J ∈ primesOver (span {(643 : ℤ)})
        (NumberField.RingOfIntegers RealField),
      900 < 643 ^ J.inertiaDeg ℤ ∨ Submodule.IsPrincipal J :=
  ⟨selectedPrime, selectedPrime.property, Or.inr selectedPrime_isPrincipal⟩

end

end BealRegular.TwentyThreeRealCertificates.Q643
