module

public import BealRegular.TwentyThreeRealCertificateBase

/-!
This file is generated by `render_23_real_certificates.mjs` from
`certificates_23_real.json`.  Corpus SHA-256:
`21e554a6a6a2b0d78efef741813a98d5269feebdbf11f9219bb6f8c03d6cc9e7`.
Do not edit this file by hand.
-/

@[expose] public section

open Ideal NumberField Polynomial RingOfIntegers

namespace BealRegular.TwentyThreeRealCertificates.Q137

open BealRegular.PrincipalIdealCertificate
open BealRegular.TwentyThreeRealCertificateBase

noncomputable section

local instance : Fact (Nat.Prime 137) := ⟨by norm_num⟩

def P : ℤ[X] := X - C 11

def Q : ℤ[X] := X ^ 10 + C 10 * X ^ 9 + C 100 * X ^ 8 + C 1109 * X ^ 7 + C 12235 * X ^ 6
  + C 134557 * X ^ 5 + C 1480071 * X ^ 4 + C 16280816 * X ^ 3 + C 179089011 * X ^ 2
  + C 1969979106 * X + C 21669770160

def A : ℤ[X] := C 1739908553

def G : ℤ[X] := X ^ 10 - X ^ 9 - C 10 * X ^ 8 + C 8 * X ^ 7 + C 36 * X ^ 6 - C 21 * X ^ 5
  - C 55 * X ^ 4 + C 20 * X ^ 3 + C 31 * X ^ 2 - C 5 * X - C 4

def Qq : ℤ[X] := C 21 * X ^ 10 - C 64 * X ^ 9 - C 229 * X ^ 8 + C 547 * X ^ 7 + C 882 * X ^ 6
  - C 1572 * X ^ 5 - C 1343 * X ^ 4 + C 1717 * X ^ 3 + C 579 * X ^ 2 - C 522 * X + C 23

def Rq : ℤ[X] := -C 21 * X ^ 9 + C 64 * X ^ 8 + C 229 * X ^ 7 - C 526 * X ^ 6 - C 925 * X ^ 5
  + C 1363 * X ^ 4 + C 1489 * X ^ 3 - C 1166 * X ^ 2 - C 599 * X + C 229

def QP : ℤ[X] := -C 2 * X ^ 10 + C 5 * X ^ 9 + C 21 * X ^ 8 - C 43 * X ^ 7 - C 78 * X ^ 6
  + C 125 * X ^ 5 + C 115 * X ^ 4 - C 139 * X ^ 3 - C 48 * X ^ 2 + C 43 * X - C 2

def RP : ℤ[X] := C 2 * X ^ 9 - C 5 * X ^ 8 - C 21 * X ^ 7 + C 41 * X ^ 6 + C 81 * X ^ 5
  - C 107 * X ^ 4 - C 125 * X ^ 3 + C 94 * X ^ 2 + C 49 * X - C 19

def C1 : ℤ[X] := X ^ 9 + C 10 * X ^ 8 + C 100 * X ^ 7 + C 1108 * X ^ 6 + C 12224 * X ^ 5
  + C 134443 * X ^ 4 + C 1478818 * X ^ 3 + C 16267018 * X ^ 2 + C 178937229 * X + C 1968309514

def C2 : ℤ[X] := C 158039450

set_option maxHeartbeats 0 in
-- Exact normalization of the displayed polynomial identity can be expensive.
set_option maxRecDepth 12000 in
/-- The factor identity in ℤ[X]. -/
theorem factorization_identity :
    P * Q + C (137 : ℤ) * A = Phi := by
  simp only [P, Q, A, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  ring

set_option maxHeartbeats 0 in
-- Exact normalization of the three displayed Bezout identities can be expensive.
set_option maxRecDepth 12000 in
/-- The three exact Bezout identities certifying the Kummer--Dedekind ideal. -/
theorem principal_identities :
    C (137 : ℤ) = G * Qq + Phi * Rq ∧
      P = G * QP + Phi * RP ∧
        G = C2 * C (137 : ℤ) + C1 * P + Phi * 0 := by
  simp only [P, G, Qq, Rq, QP, RP, C1, C2, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  constructor
  · ring
  constructor <;> ring

theorem P_monic : P.Monic := by
  simp only [P]
  monicity!

theorem map_P_irreducible :
    Irreducible (P.map (Int.castRingHom (ZMod 137))) := by
  apply Polynomial.irreducible_of_degree_eq_one
  simp only [P, Polynomial.map_sub, map_X, map_C]
  compute_degree!

theorem map_P_dvd_Phi :
    P.map (Int.castRingHom (ZMod 137)) ∣
      Phi.map (Int.castRingHom (ZMod 137)) := by
  refine ⟨Q.map (Int.castRingHom (ZMod 137)), ?_⟩
  have h := congrArg (Polynomial.map (Int.castRingHom (ZMod 137)))
    factorization_identity
  simp only [Polynomial.map_add, Polynomial.map_mul, map_C] at h
  have hq : Int.castRingHom (ZMod 137) (137 : ℤ) = 0 := by decide
  rw [hq, C_0, zero_mul, add_zero] at h
  exact h.symm

theorem map_P_mem_monicFactorsMod :
    P.map (Int.castRingHom (ZMod 137)) ∈ monicFactorsMod theta 137 := by
  rw [Multiset.mem_toFinset, Polynomial.mem_normalizedFactors_iff
    (map_monic_ne_zero (minpoly.monic theta.isIntegral))]
  refine ⟨map_P_irreducible, P_monic.map _, ?_⟩
  rw [← Phi_eq_minpoly]
  exact map_P_dvd_Phi

theorem q_not_dvd_exponent : ¬ 137 ∣ exponent theta := by
  rw [theta_exponent]
  norm_num

/-- The prime above 137 selected by the displayed linear factor. -/
noncomputable def selectedPrime :
    primesOver (span {(137 : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  (NumberField.Ideal.primesOverSpanEquivMonicFactorsMod q_not_dvd_exponent).symm
    ⟨P.map (Int.castRingHom (ZMod 137)), map_P_mem_monicFactorsMod⟩

theorem selectedPrime_mem_primesOver :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) ∈
      primesOver (span {(137 : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  selectedPrime.property

theorem selectedPrime_eq_span :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) =
      span {algebraMap ℤ (NumberField.RingOfIntegers RealField) 137, aeval theta P} := by
  exact NumberField.Ideal.primesOverSpanEquivMonicFactorsMod_symm_apply_eq_span
    q_not_dvd_exponent map_P_mem_monicFactorsMod

/-- The selected prime above 137 is principal, with generator G(theta). -/
theorem selectedPrime_isPrincipal :
    Submodule.IsPrincipal
      (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) := by
  rcases principal_identities with ⟨hq, hP, hG⟩
  exact kummerDedekindPrime_isPrincipal_of_polynomial_certificate
    (F := P) (G := G) (Phi := Phi) (QA := Qq) (QB := QP)
    (RA := Rq) (RB := RP) (RG := 0) (CA := C2) (CB := C1)
    (p := 137) theta q_not_dvd_exponent map_P_mem_monicFactorsMod
    aeval_Phi_theta hq hP hG

/-- The exact branch shape consumed by the real-subfield Minkowski criterion. -/
theorem minkowski_branch :
    ∃ J ∈ primesOver (span {(137 : ℤ)})
        (NumberField.RingOfIntegers RealField),
      900 < 137 ^ J.inertiaDeg ℤ ∨ Submodule.IsPrincipal J :=
  ⟨selectedPrime, selectedPrime.property, Or.inr selectedPrime_isPrincipal⟩

end

end BealRegular.TwentyThreeRealCertificates.Q137
