module

public import BealRegular.TwentyThreeRealCertificateBase

/-!
This file is generated by `render_23_real_certificates.mjs` from
`certificates_23_real.json`.  Corpus SHA-256:
`21e554a6a6a2b0d78efef741813a98d5269feebdbf11f9219bb6f8c03d6cc9e7`.
Do not edit this file by hand.
-/

@[expose] public section

open Ideal NumberField Polynomial RingOfIntegers

namespace BealRegular.TwentyThreeRealCertificates.Q691

open BealRegular.PrincipalIdealCertificate
open BealRegular.TwentyThreeRealCertificateBase

noncomputable section

local instance : Fact (Nat.Prime 691) := ⟨by norm_num⟩

def P : ℤ[X] := X + C 18

def Q : ℤ[X] := X ^ 10 - C 19 * X ^ 9 + C 332 * X ^ 8 - C 5967 * X ^ 7 + C 107442 * X ^ 6
  - C 1933984 * X ^ 5 + C 34811656 * X ^ 4 - C 626609773 * X ^ 3 + C 11278975949 * X ^ 2
  - C 203021567097 * X + C 3654388207740

def A : ℤ[X] := -C 95193904109

def G : ℤ[X] := X ^ 6 + X ^ 5 - C 6 * X ^ 4 - C 5 * X ^ 3 + C 9 * X ^ 2 + C 4 * X - C 2

def Qq : ℤ[X] := -C 75 * X ^ 10 + C 43 * X ^ 9 + C 667 * X ^ 8 - C 243 * X ^ 7 - C 1781 * X ^ 6
  + C 299 * X ^ 5 + C 891 * X ^ 4 - C 6 * X ^ 3 + C 1629 * X ^ 2 + C 134 * X - C 580

def Rq : ℤ[X] := C 75 * X ^ 5 + C 107 * X ^ 4 - C 303 * X ^ 3 - C 449 * X ^ 2 - C 226 * X - C 469

def QP : ℤ[X] := -C 2 * X ^ 10 + X ^ 9 + C 18 * X ^ 8 - C 5 * X ^ 7 - C 49 * X ^ 6 + C 3 * X ^ 5
  + C 27 * X ^ 4 + C 6 * X ^ 3 + C 41 * X ^ 2 + C 2 * X - C 15

def RP : ℤ[X] := C 2 * X ^ 5 + C 3 * X ^ 4 - C 8 * X ^ 3 - C 13 * X ^ 2 - C 7 * X - C 12

def C1 : ℤ[X] := X ^ 5 - C 17 * X ^ 4 + C 300 * X ^ 3 - C 5405 * X ^ 2 + C 97299 * X - C 1751378

def C2 : ℤ[X] := C 45622

set_option maxHeartbeats 0 in
-- Exact normalization of the displayed polynomial identity can be expensive.
set_option maxRecDepth 12000 in
/-- The factor identity in ℤ[X]. -/
theorem factorization_identity :
    P * Q + C (691 : ℤ) * A = Phi := by
  simp only [P, Q, A, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  ring

set_option maxHeartbeats 0 in
-- Exact normalization of the three displayed Bezout identities can be expensive.
set_option maxRecDepth 12000 in
/-- The three exact Bezout identities certifying the Kummer--Dedekind ideal. -/
theorem principal_identities :
    C (691 : ℤ) = G * Qq + Phi * Rq ∧
      P = G * QP + Phi * RP ∧
        G = C2 * C (691 : ℤ) + C1 * P + Phi * 0 := by
  simp only [P, G, Qq, Rq, QP, RP, C1, C2, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  constructor
  · ring
  constructor <;> ring

theorem P_monic : P.Monic := by
  simp only [P]
  monicity!

theorem map_P_irreducible :
    Irreducible (P.map (Int.castRingHom (ZMod 691))) := by
  apply Polynomial.irreducible_of_degree_eq_one
  simp only [P, Polynomial.map_add, map_X, map_C]
  compute_degree!

theorem map_P_dvd_Phi :
    P.map (Int.castRingHom (ZMod 691)) ∣
      Phi.map (Int.castRingHom (ZMod 691)) := by
  refine ⟨Q.map (Int.castRingHom (ZMod 691)), ?_⟩
  have h := congrArg (Polynomial.map (Int.castRingHom (ZMod 691)))
    factorization_identity
  simp only [Polynomial.map_add, Polynomial.map_mul, map_C] at h
  have hq : Int.castRingHom (ZMod 691) (691 : ℤ) = 0 := by decide
  rw [hq, C_0, zero_mul, add_zero] at h
  exact h.symm

theorem map_P_mem_monicFactorsMod :
    P.map (Int.castRingHom (ZMod 691)) ∈ monicFactorsMod theta 691 := by
  rw [Multiset.mem_toFinset, Polynomial.mem_normalizedFactors_iff
    (map_monic_ne_zero (minpoly.monic theta.isIntegral))]
  refine ⟨map_P_irreducible, P_monic.map _, ?_⟩
  rw [← Phi_eq_minpoly]
  exact map_P_dvd_Phi

theorem q_not_dvd_exponent : ¬ 691 ∣ exponent theta := by
  rw [theta_exponent]
  norm_num

/-- The prime above 691 selected by the displayed linear factor. -/
noncomputable def selectedPrime :
    primesOver (span {(691 : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  (NumberField.Ideal.primesOverSpanEquivMonicFactorsMod q_not_dvd_exponent).symm
    ⟨P.map (Int.castRingHom (ZMod 691)), map_P_mem_monicFactorsMod⟩

theorem selectedPrime_mem_primesOver :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) ∈
      primesOver (span {(691 : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  selectedPrime.property

theorem selectedPrime_eq_span :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) =
      span {algebraMap ℤ (NumberField.RingOfIntegers RealField) 691, aeval theta P} := by
  exact NumberField.Ideal.primesOverSpanEquivMonicFactorsMod_symm_apply_eq_span
    q_not_dvd_exponent map_P_mem_monicFactorsMod

/-- The selected prime above 691 is principal, with generator G(theta). -/
theorem selectedPrime_isPrincipal :
    Submodule.IsPrincipal
      (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) := by
  rcases principal_identities with ⟨hq, hP, hG⟩
  exact kummerDedekindPrime_isPrincipal_of_polynomial_certificate
    (F := P) (G := G) (Phi := Phi) (QA := Qq) (QB := QP)
    (RA := Rq) (RB := RP) (RG := 0) (CA := C2) (CB := C1)
    (p := 691) theta q_not_dvd_exponent map_P_mem_monicFactorsMod
    aeval_Phi_theta hq hP hG

/-- The exact branch shape consumed by the real-subfield Minkowski criterion. -/
theorem minkowski_branch :
    ∃ J ∈ primesOver (span {(691 : ℤ)})
        (NumberField.RingOfIntegers RealField),
      900 < 691 ^ J.inertiaDeg ℤ ∨ Submodule.IsPrincipal J :=
  ⟨selectedPrime, selectedPrime.property, Or.inr selectedPrime_isPrincipal⟩

end

end BealRegular.TwentyThreeRealCertificates.Q691
