import BealRegular.TwentyThreeOddCharacterProduct

namespace BealRegular.TwentyThreeOddCharacterProduct

#print axioms fivePowersTwentyThree_injective
#print axioms univ_zmodTwentyThree_eq_insert_zero_image_fivePowers
#print axioms weightedCharacterSum_eq_sum_fivePowers
#print axioms sum_fivePowers_eq_eval_characterSumPolynomial
#print axioms weightedCharacterSum_eq_eval_characterSumPolynomial
#print axioms evaluationAtFive_injective
#print axioms prod_X_sub_C_oddCharactersTwentyThree_eval_five_eq_rootPolynomial
#print axioms resultant_prod_X_sub_C_oddCharactersTwentyThree_eval_five
#print axioms prod_eval_characterSumPolynomial_eq_mapped_resultant
#print axioms prod_eval_characterSumPolynomial_eq_neg_three_mul_fortySix_pow_ten
#print axioms prod_weightedCharacterSum_eq_neg_three_mul_fortySix_pow_ten
#print axioms prod_oddCharactersTwentyThree_LFunction_zero_eq
#print axioms normalized_prod_oddCharactersTwentyThree_LFunction_zero_eq_three

end BealRegular.TwentyThreeOddCharacterProduct
