module

public import BealRegular.TwentyThreeRealCertificateBase

/-!
This file is generated by `render_23_real_certificates.mjs` from
`certificates_23_real.json`.  Corpus SHA-256:
`21e554a6a6a2b0d78efef741813a98d5269feebdbf11f9219bb6f8c03d6cc9e7`.
Do not edit this file by hand.
-/

@[expose] public section

open Ideal NumberField Polynomial RingOfIntegers

namespace BealRegular.TwentyThreeRealCertificates.Q599

open BealRegular.PrincipalIdealCertificate
open BealRegular.TwentyThreeRealCertificateBase

noncomputable section

local instance : Fact (Nat.Prime 599) := ⟨by norm_num⟩

def P : ℤ[X] := X + C 32

def Q : ℤ[X] := X ^ 10 - C 33 * X ^ 9 + C 1046 * X ^ 8 - C 33463 * X ^ 7 + C 1070852 * X ^ 6
  - C 34267292 * X ^ 5 + C 1096553288 * X ^ 4 - C 35089705181 * X ^ 3 + C 1122870565827 * X ^ 2
  - C 35931858106479 * X + C 1149819459407322

def A : ℤ[X] := -C 61426081303897

def G : ℤ[X] := X ^ 10 - C 9 * X ^ 8 + C 28 * X ^ 6 + X ^ 5 - C 35 * X ^ 4 - C 4 * X ^ 3
  + C 15 * X ^ 2 + C 3 * X - C 2

def Qq : ℤ[X] := C 151 * X ^ 10 - C 191 * X ^ 9 - C 1388 * X ^ 8 + C 1449 * X ^ 7 + C 4592 * X ^ 6
  - C 3219 * X ^ 5 - C 6679 * X ^ 4 + C 1576 * X ^ 3 + C 3971 * X ^ 2 + C 646 * X - C 613

def Rq : ℤ[X] := -C 151 * X ^ 9 + C 40 * X ^ 8 + C 1277 * X ^ 7 - C 132 * X ^ 6 - C 3598 * X ^ 5
  - C 622 * X ^ 4 + C 3625 * X ^ 3 + C 2008 * X ^ 2 - C 631 * X - C 627

def QP : ℤ[X] := C 8 * X ^ 10 - C 10 * X ^ 9 - C 74 * X ^ 8 + C 76 * X ^ 7 + C 247 * X ^ 6
  - C 169 * X ^ 5 - C 363 * X ^ 4 + C 82 * X ^ 3 + C 217 * X ^ 2 + C 35 * X - C 33

def RP : ℤ[X] := -C 8 * X ^ 9 + C 2 * X ^ 8 + C 68 * X ^ 7 - C 6 * X ^ 6 - C 193 * X ^ 5
  - C 36 * X ^ 4 + C 196 * X ^ 3 + C 110 * X ^ 2 - C 34 * X - C 34

def C1 : ℤ[X] := X ^ 9 - C 32 * X ^ 8 + C 1015 * X ^ 7 - C 32480 * X ^ 6 + C 1039388 * X ^ 5
  - C 33260415 * X ^ 4 + C 1064333245 * X ^ 3 - C 34058663844 * X ^ 2 + C 1089877243023 * X
  - C 34876071776733

def C2 : ℤ[X] := C 1863162432146

set_option maxHeartbeats 0 in
-- Exact normalization of the displayed polynomial identity can be expensive.
set_option maxRecDepth 12000 in
/-- The factor identity in ℤ[X]. -/
theorem factorization_identity :
    P * Q + C (599 : ℤ) * A = Phi := by
  simp only [P, Q, A, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  ring

set_option maxHeartbeats 0 in
-- Exact normalization of the three displayed Bezout identities can be expensive.
set_option maxRecDepth 12000 in
/-- The three exact Bezout identities certifying the Kummer--Dedekind ideal. -/
theorem principal_identities :
    C (599 : ℤ) = G * Qq + Phi * Rq ∧
      P = G * QP + Phi * RP ∧
        G = C2 * C (599 : ℤ) + C1 * P + Phi * 0 := by
  simp only [P, G, Qq, Rq, QP, RP, C1, C2, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  constructor
  · ring
  constructor <;> ring

theorem P_monic : P.Monic := by
  simp only [P]
  monicity!

theorem map_P_irreducible :
    Irreducible (P.map (Int.castRingHom (ZMod 599))) := by
  apply Polynomial.irreducible_of_degree_eq_one
  simp only [P, Polynomial.map_add, map_X, map_C]
  compute_degree!

theorem map_P_dvd_Phi :
    P.map (Int.castRingHom (ZMod 599)) ∣
      Phi.map (Int.castRingHom (ZMod 599)) := by
  refine ⟨Q.map (Int.castRingHom (ZMod 599)), ?_⟩
  have h := congrArg (Polynomial.map (Int.castRingHom (ZMod 599)))
    factorization_identity
  simp only [Polynomial.map_add, Polynomial.map_mul, map_C] at h
  have hq : Int.castRingHom (ZMod 599) (599 : ℤ) = 0 := by decide
  rw [hq, C_0, zero_mul, add_zero] at h
  exact h.symm

theorem map_P_mem_monicFactorsMod :
    P.map (Int.castRingHom (ZMod 599)) ∈ monicFactorsMod theta 599 := by
  rw [Multiset.mem_toFinset, Polynomial.mem_normalizedFactors_iff
    (map_monic_ne_zero (minpoly.monic theta.isIntegral))]
  refine ⟨map_P_irreducible, P_monic.map _, ?_⟩
  rw [← Phi_eq_minpoly]
  exact map_P_dvd_Phi

theorem q_not_dvd_exponent : ¬ 599 ∣ exponent theta := by
  rw [theta_exponent]
  norm_num

/-- The prime above 599 selected by the displayed linear factor. -/
noncomputable def selectedPrime :
    primesOver (span {(599 : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  (NumberField.Ideal.primesOverSpanEquivMonicFactorsMod q_not_dvd_exponent).symm
    ⟨P.map (Int.castRingHom (ZMod 599)), map_P_mem_monicFactorsMod⟩

theorem selectedPrime_mem_primesOver :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) ∈
      primesOver (span {(599 : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  selectedPrime.property

theorem selectedPrime_eq_span :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) =
      span {algebraMap ℤ (NumberField.RingOfIntegers RealField) 599, aeval theta P} := by
  exact NumberField.Ideal.primesOverSpanEquivMonicFactorsMod_symm_apply_eq_span
    q_not_dvd_exponent map_P_mem_monicFactorsMod

/-- The selected prime above 599 is principal, with generator G(theta). -/
theorem selectedPrime_isPrincipal :
    Submodule.IsPrincipal
      (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) := by
  rcases principal_identities with ⟨hq, hP, hG⟩
  exact kummerDedekindPrime_isPrincipal_of_polynomial_certificate
    (F := P) (G := G) (Phi := Phi) (QA := Qq) (QB := QP)
    (RA := Rq) (RB := RP) (RG := 0) (CA := C2) (CB := C1)
    (p := 599) theta q_not_dvd_exponent map_P_mem_monicFactorsMod
    aeval_Phi_theta hq hP hG

/-- The exact branch shape consumed by the real-subfield Minkowski criterion. -/
theorem minkowski_branch :
    ∃ J ∈ primesOver (span {(599 : ℤ)})
        (NumberField.RingOfIntegers RealField),
      900 < 599 ^ J.inertiaDeg ℤ ∨ Submodule.IsPrincipal J :=
  ⟨selectedPrime, selectedPrime.property, Or.inr selectedPrime_isPrincipal⟩

end

end BealRegular.TwentyThreeRealCertificates.Q599
