module

public import BealRegular.TwentyThreeRealCertificateBase

/-!
This file is generated by `render_23_real_certificates.mjs` from
`certificates_23_real.json`.  Corpus SHA-256:
`21e554a6a6a2b0d78efef741813a98d5269feebdbf11f9219bb6f8c03d6cc9e7`.
Do not edit this file by hand.
-/

@[expose] public section

open Ideal NumberField Polynomial RingOfIntegers

namespace BealRegular.TwentyThreeRealCertificates.Q829

open BealRegular.PrincipalIdealCertificate
open BealRegular.TwentyThreeRealCertificateBase

noncomputable section

local instance : Fact (Nat.Prime 829) := ⟨by norm_num⟩

def P : ℤ[X] := X - C 18

def Q : ℤ[X] := X ^ 10 + C 17 * X ^ 9 + C 296 * X ^ 8 + C 5337 * X ^ 7 + C 96102 * X ^ 6
  + C 1729808 * X ^ 5 + C 31136488 * X ^ 4 + C 560456819 * X ^ 3 + C 10088222777 * X ^ 2
  + C 181588009971 * X + C 3268584179472

def A : ℤ[X] := C 70970464693

def G : ℤ[X] := -X ^ 10 + C 9 * X ^ 8 - C 28 * X ^ 6 + C 2 * X ^ 5 + C 36 * X ^ 4 - C 9 * X ^ 3
  - C 19 * X ^ 2 + C 7 * X + C 3

def Qq : ℤ[X] := C 38 * X ^ 10 - C 183 * X ^ 9 - C 358 * X ^ 8 + C 1359 * X ^ 7 + C 960 * X ^ 6
  - C 2851 * X ^ 5 - C 390 * X ^ 4 + C 942 * X ^ 3 - C 781 * X ^ 2 + C 1123 * X + C 90

def Rq : ℤ[X] := C 38 * X ^ 9 - C 145 * X ^ 8 - C 465 * X ^ 7 + C 749 * X ^ 6 + C 1282 * X ^ 5
  - C 1041 * X ^ 4 - C 210 * X ^ 3 + C 707 * X ^ 2 - C 645 * X + C 559

def QP : ℤ[X] := -X ^ 10 + C 4 * X ^ 9 + C 9 * X ^ 8 - C 30 * X ^ 7 - C 23 * X ^ 6 + C 64 * X ^ 5
  + C 8 * X ^ 4 - C 23 * X ^ 3 + C 19 * X ^ 2 - C 24 * X - C 2

def RP : ℤ[X] := -X ^ 9 + C 3 * X ^ 8 + C 11 * X ^ 7 - C 16 * X ^ 6 - C 29 * X ^ 5 + C 24 * X ^ 4
  + C 5 * X ^ 3 - C 17 * X ^ 2 + C 15 * X - C 12

def C1 : ℤ[X] := -X ^ 9 - C 18 * X ^ 8 - C 315 * X ^ 7 - C 5670 * X ^ 6 - C 102088 * X ^ 5
  - C 1837582 * X ^ 4 - C 33076440 * X ^ 3 - C 595375929 * X ^ 2 - C 10716766741 * X
  - C 192901801331

def C2 : ℤ[X] := -C 4188458895

set_option maxHeartbeats 0 in
-- Exact normalization of the displayed polynomial identity can be expensive.
set_option maxRecDepth 12000 in
/-- The factor identity in ℤ[X]. -/
theorem factorization_identity :
    P * Q + C (829 : ℤ) * A = Phi := by
  simp only [P, Q, A, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  ring

set_option maxHeartbeats 0 in
-- Exact normalization of the three displayed Bezout identities can be expensive.
set_option maxRecDepth 12000 in
/-- The three exact Bezout identities certifying the Kummer--Dedekind ideal. -/
theorem principal_identities :
    C (829 : ℤ) = G * Qq + Phi * Rq ∧
      P = G * QP + Phi * RP ∧
        G = C2 * C (829 : ℤ) + C1 * P + Phi * 0 := by
  simp only [P, G, Qq, Rq, QP, RP, C1, C2, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  constructor
  · ring
  constructor <;> ring

theorem P_monic : P.Monic := by
  simp only [P]
  monicity!

theorem map_P_irreducible :
    Irreducible (P.map (Int.castRingHom (ZMod 829))) := by
  apply Polynomial.irreducible_of_degree_eq_one
  simp only [P, Polynomial.map_sub, map_X, map_C]
  compute_degree!

theorem map_P_dvd_Phi :
    P.map (Int.castRingHom (ZMod 829)) ∣
      Phi.map (Int.castRingHom (ZMod 829)) := by
  refine ⟨Q.map (Int.castRingHom (ZMod 829)), ?_⟩
  have h := congrArg (Polynomial.map (Int.castRingHom (ZMod 829)))
    factorization_identity
  simp only [Polynomial.map_add, Polynomial.map_mul, map_C] at h
  have hq : Int.castRingHom (ZMod 829) (829 : ℤ) = 0 := by decide
  rw [hq, C_0, zero_mul, add_zero] at h
  exact h.symm

theorem map_P_mem_monicFactorsMod :
    P.map (Int.castRingHom (ZMod 829)) ∈ monicFactorsMod theta 829 := by
  rw [Multiset.mem_toFinset, Polynomial.mem_normalizedFactors_iff
    (map_monic_ne_zero (minpoly.monic theta.isIntegral))]
  refine ⟨map_P_irreducible, P_monic.map _, ?_⟩
  rw [← Phi_eq_minpoly]
  exact map_P_dvd_Phi

theorem q_not_dvd_exponent : ¬ 829 ∣ exponent theta := by
  rw [theta_exponent]
  norm_num

/-- The prime above 829 selected by the displayed linear factor. -/
noncomputable def selectedPrime :
    primesOver (span {(829 : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  (NumberField.Ideal.primesOverSpanEquivMonicFactorsMod q_not_dvd_exponent).symm
    ⟨P.map (Int.castRingHom (ZMod 829)), map_P_mem_monicFactorsMod⟩

theorem selectedPrime_mem_primesOver :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) ∈
      primesOver (span {(829 : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  selectedPrime.property

theorem selectedPrime_eq_span :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) =
      span {algebraMap ℤ (NumberField.RingOfIntegers RealField) 829, aeval theta P} := by
  exact NumberField.Ideal.primesOverSpanEquivMonicFactorsMod_symm_apply_eq_span
    q_not_dvd_exponent map_P_mem_monicFactorsMod

/-- The selected prime above 829 is principal, with generator G(theta). -/
theorem selectedPrime_isPrincipal :
    Submodule.IsPrincipal
      (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) := by
  rcases principal_identities with ⟨hq, hP, hG⟩
  exact kummerDedekindPrime_isPrincipal_of_polynomial_certificate
    (F := P) (G := G) (Phi := Phi) (QA := Qq) (QB := QP)
    (RA := Rq) (RB := RP) (RG := 0) (CA := C2) (CB := C1)
    (p := 829) theta q_not_dvd_exponent map_P_mem_monicFactorsMod
    aeval_Phi_theta hq hP hG

/-- The exact branch shape consumed by the real-subfield Minkowski criterion. -/
theorem minkowski_branch :
    ∃ J ∈ primesOver (span {(829 : ℤ)})
        (NumberField.RingOfIntegers RealField),
      900 < 829 ^ J.inertiaDeg ℤ ∨ Submodule.IsPrincipal J :=
  ⟨selectedPrime, selectedPrime.property, Or.inr selectedPrime_isPrincipal⟩

end

end BealRegular.TwentyThreeRealCertificates.Q829
