import BealRegular.TwentyThreeAnalyticClassNumber

namespace BealRegular.TwentyThreeAnalyticClassNumber

#print axioms maximalRealSubfield_dedekindZeta_residue
#print axioms cyclotomic_dedekindZeta_residue
#print axioms scaledDedekindZetaResidueRatio_eq_classNumber_div_indexRealUnits
#print axioms classNumber_div_indexRealUnits_eq_three_of_oddCharacterAnalyticBridge
#print axioms classNumber_eq_three_mul_indexRealUnits_of_oddCharacterAnalyticBridge
#print axioms classNumber_eq_three_of_oddCharacterAnalyticBridge
#print axioms isRegularPrime_twentyThree_of_oddCharacterAnalyticBridge
#print axioms fermatLastTheoremTwentyThree_of_oddCharacterAnalyticBridge

end BealRegular.TwentyThreeAnalyticClassNumber
