#!/usr/bin/env node

/*
 * Render the exact p = 23 maximal-real-subfield certificates as small Lean
 * modules.  This script intentionally uses only Node's standard library.
 *
 * Usage:
 *   node render_23_real_certificates.mjs [input.json] [output-directory]
 */

import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { basename, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = fileURLToPath(new URL(".", import.meta.url));
const inputPath = resolve(process.argv[2] ?? `${here}/certificates_23_real.json`);
const outputDirectory = resolve(process.argv[3] ?? `${here}/../BealRegular`);

const sourceData = JSON.parse(await readFile(inputPath, "utf8"));
const certificates = [...sourceData.certificates].sort((left, right) => left.q - right.q);

function canonicalize(value) {
  if (Array.isArray(value)) return value.map(canonicalize);
  if (value !== null && typeof value === "object") {
    return Object.fromEntries(Object.keys(value).sort().map((key) => [key, canonicalize(value[key])]));
  }
  return value;
}

const canonicalData = { ...sourceData, certificates };
const canonicalJson = `${JSON.stringify(canonicalize(canonicalData), null, 2)}\n`;
const corpusDigest = createHash("sha256").update(canonicalJson).digest("hex");

function normalize(polynomial) {
  const result = polynomial.map(BigInt);
  while (result.length > 0 && result.at(-1) === 0n) result.pop();
  return result;
}

function polynomial(coefficients) {
  const values = normalize(coefficients);
  if (values.length === 0) return "0";
  const terms = [];
  for (let exponent = values.length - 1; exponent >= 0; exponent -= 1) {
    const coefficient = values[exponent];
    if (coefficient === 0n) continue;
    const negative = coefficient < 0n;
    const magnitude = negative ? -coefficient : coefficient;
    const variable = exponent === 0 ? "" : exponent === 1 ? "X" : `X ^ ${exponent}`;
    const body = exponent === 0
      ? `C ${magnitude}`
      : magnitude === 1n ? variable : `C ${magnitude} * ${variable}`;
    terms.push({ negative, body });
  }
  return terms.map(({ negative, body }, index) => {
    if (index === 0) return negative ? `-${body}` : body;
    return negative ? ` - ${body}` : ` + ${body}`;
  }).join("");
}

function wrappedDefinition(name, coefficients) {
  const expression = polynomial(coefficients);
  const prefix = `def ${name} : ℤ[X] :=`;
  if (`${prefix} ${expression}`.length <= 100) return `${prefix} ${expression}`;
  const pieces = expression.split(/ (?=[+-] )/);
  const lines = [];
  let line = prefix;
  for (const piece of pieces) {
    if (`${line} ${piece}`.length > 100 && line !== prefix) {
      lines.push(line);
      line = `  ${piece}`;
    } else {
      line += ` ${piece}`;
    }
  }
  lines.push(line);
  return lines.join("\n");
}

function generatedHeader(sourceName) {
  return `/-!\nThis file is generated by \`render_23_real_certificates.mjs\` from\n\`${sourceName}\`.  Corpus SHA-256:\n\`${corpusDigest}\`.\nDo not edit this file by hand.\n-/`;
}

function certificateSource(certificate) {
  const q = certificate.q;
  const namespace = `BealRegular.TwentyThreeRealCertificates.Q${q}`;
  const names = ["P", "Q", "A", "G", "Qq", "Rq", "QP", "RP", "C1", "C2"];
  const polynomials = Object.fromEntries(names.map((name) => [name, normalize(certificate[name])]));
  const definitions = names.map((name) => wrappedDefinition(name, polynomials[name])).join("\n\n");
  const mapPOperation = polynomials.P[0] < 0n ? "Polynomial.map_sub" : "Polynomial.map_add";

  return `module

public import BealRegular.TwentyThreeRealCertificateBase

${generatedHeader(basename(inputPath))}

@[expose] public section

open Ideal NumberField Polynomial RingOfIntegers

namespace ${namespace}

open BealRegular.PrincipalIdealCertificate
open BealRegular.TwentyThreeRealCertificateBase

noncomputable section

local instance : Fact (Nat.Prime ${q}) := ⟨by norm_num⟩

${definitions}

set_option maxHeartbeats 0 in
-- Exact normalization of the displayed polynomial identity can be expensive.
set_option maxRecDepth 12000 in
/-- The factor identity in ℤ[X]. -/
theorem factorization_identity :
    P * Q + C (${q} : ℤ) * A = Phi := by
  simp only [P, Q, A, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  ring

set_option maxHeartbeats 0 in
-- Exact normalization of the three displayed Bezout identities can be expensive.
set_option maxRecDepth 12000 in
/-- The three exact Bezout identities certifying the Kummer--Dedekind ideal. -/
theorem principal_identities :
    C (${q} : ℤ) = G * Qq + Phi * Rq ∧
      P = G * QP + Phi * RP ∧
        G = C2 * C (${q} : ℤ) + C1 * P + Phi * 0 := by
  simp only [P, G, Qq, Rq, QP, RP, C1, C2, Phi,
    BealRegular.TwentyThreeRealSubfield.realSubfieldPolynomial,
    map_ofNat, C_1]
  constructor
  · ring
  constructor <;> ring

theorem P_monic : P.Monic := by
  simp only [P]
  monicity!

theorem map_P_irreducible :
    Irreducible (P.map (Int.castRingHom (ZMod ${q}))) := by
  apply Polynomial.irreducible_of_degree_eq_one
  simp only [P, ${mapPOperation}, map_X, map_C]
  compute_degree!

theorem map_P_dvd_Phi :
    P.map (Int.castRingHom (ZMod ${q})) ∣
      Phi.map (Int.castRingHom (ZMod ${q})) := by
  refine ⟨Q.map (Int.castRingHom (ZMod ${q})), ?_⟩
  have h := congrArg (Polynomial.map (Int.castRingHom (ZMod ${q})))
    factorization_identity
  simp only [Polynomial.map_add, Polynomial.map_mul, map_C] at h
  have hq : Int.castRingHom (ZMod ${q}) (${q} : ℤ) = 0 := by decide
  rw [hq, C_0, zero_mul, add_zero] at h
  exact h.symm

theorem map_P_mem_monicFactorsMod :
    P.map (Int.castRingHom (ZMod ${q})) ∈ monicFactorsMod theta ${q} := by
  rw [Multiset.mem_toFinset, Polynomial.mem_normalizedFactors_iff
    (map_monic_ne_zero (minpoly.monic theta.isIntegral))]
  refine ⟨map_P_irreducible, P_monic.map _, ?_⟩
  rw [← Phi_eq_minpoly]
  exact map_P_dvd_Phi

theorem q_not_dvd_exponent : ¬ ${q} ∣ exponent theta := by
  rw [theta_exponent]
  norm_num

/-- The prime above ${q} selected by the displayed linear factor. -/
noncomputable def selectedPrime :
    primesOver (span {(${q} : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  (NumberField.Ideal.primesOverSpanEquivMonicFactorsMod q_not_dvd_exponent).symm
    ⟨P.map (Int.castRingHom (ZMod ${q})), map_P_mem_monicFactorsMod⟩

theorem selectedPrime_mem_primesOver :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) ∈
      primesOver (span {(${q} : ℤ)}) (NumberField.RingOfIntegers RealField) :=
  selectedPrime.property

theorem selectedPrime_eq_span :
    (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) =
      span {algebraMap ℤ (NumberField.RingOfIntegers RealField) ${q}, aeval theta P} := by
  exact NumberField.Ideal.primesOverSpanEquivMonicFactorsMod_symm_apply_eq_span
    q_not_dvd_exponent map_P_mem_monicFactorsMod

/-- The selected prime above ${q} is principal, with generator G(theta). -/
theorem selectedPrime_isPrincipal :
    Submodule.IsPrincipal
      (selectedPrime : Ideal (NumberField.RingOfIntegers RealField)) := by
  rcases principal_identities with ⟨hq, hP, hG⟩
  exact kummerDedekindPrime_isPrincipal_of_polynomial_certificate
    (F := P) (G := G) (Phi := Phi) (QA := Qq) (QB := QP)
    (RA := Rq) (RB := RP) (RG := 0) (CA := C2) (CB := C1)
    (p := ${q}) theta q_not_dvd_exponent map_P_mem_monicFactorsMod
    aeval_Phi_theta hq hP hG

/-- The exact branch shape consumed by the real-subfield Minkowski criterion. -/
theorem minkowski_branch :
    ∃ J ∈ primesOver (span {(${q} : ℤ)})
        (NumberField.RingOfIntegers RealField),
      900 < ${q} ^ J.inertiaDeg ℤ ∨ Submodule.IsPrincipal J :=
  ⟨selectedPrime, selectedPrime.property, Or.inr selectedPrime_isPrincipal⟩

end

end ${namespace}
`;
}

const baseSource = `module

public import BealRegular.PrincipalIdealCertificate
public import BealRegular.TwentyThreeRealSubfieldRingOfIntegers

${generatedHeader(basename(inputPath))}

@[expose] public section

open NumberField Polynomial RingOfIntegers

namespace BealRegular.TwentyThreeRealCertificateBase

open BealRegular.TwentyThreeRealSubfield
open BealRegular.TwentyThreeRealSubfieldRingOfIntegers

noncomputable section

/-- The degree-eleven maximal real subfield of the 23rd cyclotomic field. -/
abbrev RealField := NumberField.maximalRealSubfield (CyclotomicField 23 ℚ)

/-- The integral real-subfield generator alpha. -/
abbrev theta : NumberField.RingOfIntegers RealField := alphaInteger

/-- The minimal polynomial of theta. -/
abbrev Phi : ℤ[X] := realSubfieldPolynomial

theorem Phi_eq_minpoly : Phi = minpoly ℤ theta := by
  exact minpoly_int_alphaInteger.symm

theorem aeval_Phi_theta : aeval theta Phi = 0 := by
  exact aeval_realSubfieldPolynomial_alphaInteger

theorem theta_exponent : exponent theta = 1 := alphaInteger_exponent

end


end BealRegular.TwentyThreeRealCertificateBase
`;

const aggregateImports = certificates
  .map(({ q }) => `public import BealRegular.TwentyThreeRealCertificate${q}`)
  .join("\n");
const aggregateSource = `module

${aggregateImports}

${generatedHeader(basename(inputPath))}
`;

const auditLines = certificates.flatMap(({ q }) => {
  const prefix = `BealRegular.TwentyThreeRealCertificates.Q${q}`;
  return [
    `#print axioms ${prefix}.factorization_identity`,
    `#print axioms ${prefix}.principal_identities`,
    `#print axioms ${prefix}.map_P_mem_monicFactorsMod`,
    `#print axioms ${prefix}.selectedPrime_isPrincipal`,
    `#print axioms ${prefix}.minkowski_branch`,
  ];
});
const auditSource = `import BealRegular.TwentyThreeRealCertificates

${generatedHeader(basename(inputPath))}

${auditLines.join("\n")}
`;

async function writeIfChanged(path, source) {
  try {
    if (await readFile(path, "utf8") === source) return false;
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
  await writeFile(path, source);
  return true;
}

await mkdir(outputDirectory, { recursive: true });
const expected = new Set([
  "TwentyThreeRealCertificateBase.lean",
  "TwentyThreeRealCertificates.lean",
  "TwentyThreeRealCertificatesAudit.lean",
  ...certificates.map(({ q }) => `TwentyThreeRealCertificate${q}.lean`),
]);
for (const entry of await readdir(outputDirectory)) {
  if (!expected.has(entry) && /^TwentyThreeRealCertificate[0-9]+\.lean$/.test(entry)) {
    await rm(resolve(outputDirectory, entry));
  }
}

let changed = 0;
changed += Number(await writeIfChanged(resolve(outputDirectory, "TwentyThreeRealCertificateBase.lean"), baseSource));
for (const certificate of certificates) {
  changed += Number(await writeIfChanged(
    resolve(outputDirectory, `TwentyThreeRealCertificate${certificate.q}.lean`),
    certificateSource(certificate),
  ));
}
changed += Number(await writeIfChanged(resolve(outputDirectory, "TwentyThreeRealCertificates.lean"), aggregateSource));
changed += Number(await writeIfChanged(resolve(outputDirectory, "TwentyThreeRealCertificatesAudit.lean"), auditSource));

console.log(JSON.stringify({
  input: inputPath,
  output: outputDirectory,
  certificates: certificates.length,
  corpusSha256: corpusDigest,
  files: expected.size,
  changed,
}));
